-- Insert new scholarships (skip existing MEXT)
INSERT INTO scholarships (id, name_en, name_km, provider_en, provider_km, description_en, description_km, type, coverage_en, coverage_km, eligibility_en, eligibility_km, application_url, deadline, is_active) VALUES
('22222222-2222-2222-2222-222222222207', 'MoEYS University Scholarship', 'អាហារូបករណ៍សាកលវិទ្យាល័យ MoEYS', 'Ministry of Education, Youth and Sport', 'ក្រសួងអប់រំ យុវជន និងកីឡា', 'Government scholarship for Bac II graduates to study at 42 national and private universities including RUPP, ITC, and NUM.', 'អាហារូបករណ៍រដ្ឋាភិបាលសម្រាប់និស្សិតជាប់ Bac II ដើម្បីសិក្សានៅសាកលវិទ្យាល័យជាតិ និងឯកជន ៤២ រួមទាំង RUPP ITC និង NUM។', 'full', 'Full tuition waiver + monthly living allowance', 'លើកលែងថ្លៃសិក្សាទាំងស្រុង + ប្រាក់ឧបត្ថម្ភរស់នៅប្រចាំខែ', 'Bac II graduates (under 25), Grade A–D', 'និស្សិតជាប់ Bac II (អាយុក្រោម ២៥ឆ្នាំ) ពិន្ទុ A ដល់ D', NULL, '2026-08-31', true),
('22222222-2222-2222-2222-222222222208', 'Techo Digital Talent Scholarship', 'អាហារូបករណ៍ Techo Digital Talent', 'Ministry of Post and Telecommunications', 'ក្រសួងប្រៃសណីយ៍ និងទូរគមនាគមន៍', 'Scholarship for IT and digital fields at CADT, ITC, RUPP, AUPP and other institutions.', 'អាហារូបករណ៍សម្រាប់វិស័យ IT និងឌីជីថលនៅ CADT ITC RUPP AUPP និងស្ថាប័នផ្សេងៗ។', 'full', 'Full tuition waiver', 'លើកលែងថ្លៃសិក្សាទាំងស្រុង', 'Bac II graduates (Grade C or above)', 'និស្សិតជាប់ Bac II (ពិន្ទុ C ឡើង)', NULL, '2026-09-30', true),
('22222222-2222-2222-2222-222222222209', 'Techo Sen Institute Scholarship', 'អាហារូបករណ៍វិទ្យាស្ថាន Techo Sen', 'Ministry of Transport', 'ក្រសួងដឹកជញ្ជូន', 'Scholarship for infrastructure, transport and logistics engineering at Techo Sen Institute in Phnom Penh.', 'អាហារូបករណ៍សម្រាប់វិស្វកម្មហេដ្ឋារចនាសម្ព័ន្ធ ដឹកជញ្ជូន និងភស្តុភារនៅវិទ្យាស្ថាន Techo Sen ភ្នំពេញ។', 'full', 'Full tuition (top 50) or 50% (female students)', 'ថ្លៃសិក្សាទាំងស្រុង (កំពូល ៥០) ឬ ៥០% (សិស្សស្រី)', 'High school graduates', 'និស្សិតបញ្ចប់វិទ្យាល័យ', NULL, '2026-01-31', true),
('22222222-2222-2222-2222-222222222210', 'EU-Cambodia Partnership Scholarship', 'អាហារូបករណ៍ភាពជាដៃគូ EU-កម្ពុជា', 'European Union / MoEYS', 'សហភាពអឺរ៉ុប / ក្រសួងអប់រំ', 'EU-funded scholarship focused on STEM fields at Cambodian public higher education institutions.', 'អាហារូបករណ៍ដែលផ្តល់មូលនិធិដោយ EU ផ្តោតលើវិស័យ STEM នៅស្ថាប័នឧត្តមសិក្សាសាធារណៈកម្ពុជា។', 'full', 'Full tuition + monthly living allowance', 'ថ្លៃសិក្សាទាំងស្រុង + ប្រាក់ឧបត្ថម្ភរស់នៅប្រចាំខែ', 'Bac II graduates, nominated through MoEYS', 'និស្សិតជាប់ Bac II តាមរយៈការតែងតាំង MoEYS', NULL, NULL, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO scholarships (id, name_en, name_km, provider_en, provider_km, description_en, description_km, type, coverage_en, coverage_km, eligibility_en, eligibility_km, application_url, deadline, is_active) VALUES
('22222222-2222-2222-2222-222222222211', 'World Bank GEIP Scholarship', 'អាហារូបករណ៍ធនាគារពិភពលោក GEIP', 'World Bank', 'ធនាគារពិភពលោក', 'Scholarship supporting secondary and higher education students through school grants and student subsidies.', 'អាហារូបករណ៍គាំទ្រសិស្សមធ្យមសិក្សា និងឧត្តមសិក្សាតាមរយៈជំនួយសាលា និងប្រាក់ឧបត្ថម្ភសិស្ស។', 'grant', 'School grants + student subsidies', 'ជំនួយសាលា + ប្រាក់ឧបត្ថម្ភសិស្ស', 'Secondary and higher education students (applied through school/MoEYS)', 'សិស្សមធ្យមសិក្សា និងឧត្តមសិក្សា (ដាក់ពាក្យតាមរយៈសាលា/MoEYS)', NULL, NULL, true),
('22222222-2222-2222-2222-222222222212', 'MoEYS PAP 12 Secondary Education Scholarship', 'អាហារូបករណ៍មធ្យមសិក្សា PAP 12 MoEYS', 'MoEYS (GPE/UNICEF support)', 'ក្រសួងអប់រំ (គាំទ្រដោយ GPE/UNICEF)', 'Cash transfer scholarship for students from poor households in grades 7-12 across 812+ schools nationwide.', 'អាហារូបករណ៍ផ្ទេរប្រាក់សម្រាប់សិស្សពីគ្រួសារក្រីក្រថ្នាក់ទី ៧-១២ នៅសាលា ៨១២+ ទូទាំងប្រទេស។', 'grant', '$60-90/year cash transfer (paid in 3 installments)', 'ផ្ទេរប្រាក់ $៦០-៩០/ឆ្នាំ (បង់ ៣ ដង)', 'Students from poor households (grades 7-12), ID-Poor card required', 'សិស្សពីគ្រួសារក្រីក្រ (ថ្នាក់ទី ៧-១២) ត្រូវការប័ណ្ណ IDPoor', NULL, NULL, true),
('22222222-2222-2222-2222-222222222213', 'Room to Read Girls Education Program', 'កម្មវិធីអប់រំស្រីរបស់ Room to Read', 'Room to Read', 'Room to Read', 'Girls education support program providing school supplies, uniforms, transport, and mentoring in 40+ secondary schools across 5 provinces.', 'កម្មវិធីគាំទ្រការអប់រំស្រី ផ្តល់សម្ភារៈសិក្សា ឯកសណ្ឋាន ការដឹកជញ្ជូន និងការណែនាំនៅសាលាមធ្យមសិក្សា ៤០+ នៅ ៥ ខេត្ត។', 'full', 'School supplies, uniforms, transport + mentoring', 'សម្ភារៈសិក្សា ឯកសណ្ឋាន ការដឹកជញ្ជូន + ការណែនាំ', 'Female secondary school students (ages 12-18)', 'សិស្សស្រីមធ្យមសិក្សា (អាយុ ១២-១៨ឆ្នាំ)', NULL, NULL, true),
('22222222-2222-2222-2222-222222222214', 'EDF Cambodia Scholarship', 'អាហារូបករណ៍ EDF Cambodia', 'EDF International Foundation', 'មូលនិធិអន្តរជាតិ EDF', 'Scholarship for rural poor students in lower secondary education in Kampong Chhnang, Takeo and other provinces.', 'អាហារូបករណ៍សម្រាប់សិស្សក្រីក្រជនបទក្នុងមធ្យមសិក្សាបឋម នៅកំពង់ឆ្នាំង តាកែវ និងខេត្តផ្សេងៗ។', 'full', 'Scholarship + textbooks + bicycle', 'អាហារូបករណ៍ + សៀវភៅសិក្សា + កង់', 'Rural poor students (lower secondary education)', 'សិស្សក្រីក្រជនបទ (មធ្យមសិក្សាបឋម)', NULL, NULL, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO scholarships (id, name_en, name_km, provider_en, provider_km, description_en, description_km, type, coverage_en, coverage_km, eligibility_en, eligibility_km, application_url, deadline, is_active) VALUES
('22222222-2222-2222-2222-222222222215', 'KAPE Programs (IBEC etc.)', 'កម្មវិធី KAPE (IBEC ល។)', 'KAPE', 'KAPE', 'Cambodia''s largest education NGO supporting 150,000+ students across 300+ schools in 13 provinces with scholarships, supplies, and vocational training.', 'អង្គការអប់រំធំបំផុតកម្ពុជា គាំទ្រសិស្ស ១៥០,០០០+ នៅសាលា ៣០០+ ក្នុង ១៣ ខេត្ត ជាមួយអាហារូបករណ៍ សម្ភារៈ និងបណ្តុះបណ្តាលវិជ្ជាជីវៈ។', 'full', 'Scholarships, school supplies, school support', 'អាហារូបករណ៍ សម្ភារៈសិក្សា ជំនួយសាលា', 'Students from poor and vulnerable backgrounds (all education levels)', 'សិស្សពីគ្រួសារក្រីក្រ និងងាយរងគ្រោះ (គ្រប់កម្រិតសិក្សា)', NULL, NULL, true),
('22222222-2222-2222-2222-222222222216', 'CSH Cambodia Scholarship', 'អាហារូបករណ៍ CSH Cambodia', 'CSH Cambodia', 'CSH Cambodia', 'Scholarship covering tuition for students from poor households, with priority for ID-Poor card holders.', 'អាហារូបករណ៍គ្របដណ្តប់ថ្លៃសិក្សាសម្រាប់សិស្សពីគ្រួសារក្រីក្រ ដោយអទិភាពដល់អ្នកមានប័ណ្ណ IDPoor។', 'full', 'ID-Poor: 100% tuition; Others: 50% tuition', 'IDPoor: ១០០% ថ្លៃសិក្សា; ផ្សេងៗ: ៥០% ថ្លៃសិក្សា', 'Students from poor households (ID-Poor card holders priority)', 'សិស្សពីគ្រួសារក្រីក្រ (អទិភាពអ្នកមានប័ណ្ណ IDPoor)', NULL, NULL, true),
('22222222-2222-2222-2222-222222222217', 'Cambodian Village Fund Scholarship', 'អាហារូបករណ៍មូលនិធិភូមិកម្ពុជា', 'Cambodian Village Fund (CVF)', 'មូលនិធិភូមិកម្ពុជា (CVF)', 'Comprehensive scholarship for rural students in Battambang covering tuition, dormitory, uniforms, textbooks, and English classes.', 'អាហារូបករណ៍ទូលំទូលាយសម្រាប់សិស្សជនបទនៅបាត់ដំបង គ្របដណ្តប់ថ្លៃសិក្សា បន្ទប់គេង ឯកសណ្ឋាន សៀវភៅ និងថ្នាក់អង់គ្លេស។', 'full', '$1,600/year (tuition, dormitory, uniforms, textbooks, English classes)', '$១,៦០០/ឆ្នាំ (ថ្លៃសិក្សា បន្ទប់គេង ឯកសណ្ឋាន សៀវភៅ ថ្នាក់អង់គ្លេស)', 'Rural students grades 7-12 in Battambang province', 'សិស្សជនបទថ្នាក់ទី ៧-១២ នៅខេត្តបាត់ដំបង', NULL, NULL, true),
('22222222-2222-2222-2222-222222222218', 'Harpswell Foundation Scholarship', 'អាហារូបករណ៍មូលនិធិ Harpswell', 'Harpswell Foundation', 'មូលនិធិ Harpswell', 'Scholarship for female university students from low-income backgrounds, providing tuition, housing, and leadership education in Phnom Penh.', 'អាហារូបករណ៍សម្រាប់និស្សិតស្រីសាកលវិទ្យាល័យពីគ្រួសារមានចំណូលទាប ផ្តល់ថ្លៃសិក្សា កន្លែងស្នាក់នៅ និងការអប់រំភាពជាអ្នកដឹកនាំនៅភ្នំពេញ។', 'full', 'Tuition, housing, leadership education', 'ថ្លៃសិក្សា កន្លែងស្នាក់នៅ ការអប់រំភាពជាអ្នកដឹកនាំ', 'Female university students from low-income families', 'និស្សិតស្រីសាកលវិទ្យាល័យពីគ្រួសារមានចំណូលទាប', NULL, NULL, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO scholarships (id, name_en, name_km, provider_en, provider_km, description_en, description_km, type, coverage_en, coverage_km, eligibility_en, eligibility_km, application_url, deadline, is_active) VALUES
('22222222-2222-2222-2222-222222222219', 'Chen Zhi Scholarship (Prince Foundation)', 'អាហារូបករណ៍ Chen Zhi (មូលនិធិ Prince)', 'Prince Foundation', 'មូលនិធិ Prince', 'Prestigious scholarship for Bac II graduates to study IT, civil engineering, business, media, and digital economy at RUPP, ITC, or NUM.', 'អាហារូបករណ៍មានកិត្យានុភាពសម្រាប់និស្សិតជាប់ Bac II ដើម្បីសិក្សា IT វិស្វកម្មសំណង់ ពាណិជ្ជកម្ម ប្រព័ន្ធផ្សព្វផ្សាយ និងសេដ្ឋកិច្ចឌីជីថលនៅ RUPP ITC ឬ NUM។', 'full', 'Full tuition + monthly allowance + internship opportunities', 'ថ្លៃសិក្សាទាំងស្រុង + ប្រាក់ឧបត្ថម្ភប្រចាំខែ + ឱកាសកម្មសិក្សា', 'Bac II graduates (Cambodian nationals), apply online Jan 15 - Feb 15', 'និស្សិតជាប់ Bac II (ពលរដ្ឋខ្មែរ) ដាក់ពាក្យអនឡាញ ១៥ មករា - ១៥ កុម្ភៈ', NULL, '2026-02-15', true),
('22222222-2222-2222-2222-222222222220', 'Maybank Cambodia Scholarship', 'អាហារូបករណ៍ Maybank Cambodia', 'Maybank Cambodia', 'Maybank Cambodia', 'Scholarship for first-year university students from families with annual income under $25,000.', 'អាហារូបករណ៍សម្រាប់និស្សិតឆ្នាំទី ១ ពីគ្រួសារមានចំណូលក្រោម $២៥,០០០/ឆ្នាំ។', 'full', 'Full tuition + PC + books + insurance + living allowance', 'ថ្លៃសិក្សាទាំងស្រុង + កុំព្យូទ័រ + សៀវភៅ + ធានារ៉ាប់រង + ប្រាក់ឧបត្ថម្ភរស់នៅ', 'First-year university students, family income under $25,000/year', 'និស្សិតឆ្នាំទី ១ សាកលវិទ្យាល័យ ចំណូលគ្រួសារក្រោម $២៥,០០០/ឆ្នាំ', NULL, '2026-04-28', true),
('22222222-2222-2222-2222-222222222221', 'AUPP Techo Digital Talent Scholarship', 'អាហារូបករណ៍ Techo Digital Talent AUPP', 'Ministry of Post and Telecommunications x AUPP', 'ក្រសួងប្រៃសណីយ៍ x AUPP', 'Scholarship for IT, cloud computing, cybersecurity, and software development at AUPP.', 'អាហារូបករណ៍សម្រាប់ IT ក្លោដកុំព្យូទីង សន្តិសុខអ៊ីនធឺណិត និងការអភិវឌ្ឍន៍កម្មវិធីនៅ AUPP។', 'full', 'Full tuition', 'ថ្លៃសិក្សាទាំងស្រុង', 'Bac II graduates (Grade C or above), must pass math/logic/English exam', 'និស្សិតជាប់ Bac II (ពិន្ទុ C ឡើង) ត្រូវប្រឡងគណិត/ឡូជីក/អង់គ្លេស', NULL, '2026-09-30', true),
('22222222-2222-2222-2222-222222222222', 'AUPP AMT Scholarship', 'អាហារូបករណ៍ AMT AUPP', 'Hun Sen Association (AMT)', 'សមាគម Hun Sen (AMT)', 'Full tuition scholarship for Bac II graduates at AUPP across all majors.', 'អាហារូបករណ៍ថ្លៃសិក្សាទាំងស្រុងសម្រាប់និស្សិតជាប់ Bac II នៅ AUPP គ្រប់ជំនាញ។', 'full', 'Full tuition', 'ថ្លៃសិក្សាទាំងស្រុង', 'Bac II graduates', 'និស្សិតជាប់ Bac II', NULL, NULL, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO scholarships (id, name_en, name_km, provider_en, provider_km, description_en, description_km, type, coverage_en, coverage_km, eligibility_en, eligibility_km, application_url, deadline, is_active) VALUES
('22222222-2222-2222-2222-222222222223', 'AUPP UYFC Scholarship', 'អាហារូបករណ៍ UYFC AUPP', 'Union of Youth Federations of Cambodia (UYFC)', 'សហព័ន្ធសមាគមយុវជនកម្ពុជា (UYFC)', 'Full tuition scholarship for 15 Bac II graduates at AUPP.', 'អាហារូបករណ៍ថ្លៃសិក្សាទាំងស្រុងសម្រាប់និស្សិតជាប់ Bac II ចំនួន ១៥ នាក់នៅ AUPP។', 'full', 'Full tuition', 'ថ្លៃសិក្សាទាំងស្រុង', 'Bac II graduates', 'និស្សិតជាប់ Bac II', NULL, NULL, true),
('22222222-2222-2222-2222-222222222224', 'University of Cambodia Hun Sen Scholarship', 'អាហារូបករណ៍សម្តេច ហ៊ុន សែន សាកលវិទ្យាល័យកម្ពុជា', 'University of Cambodia', 'សាកលវិទ្យាល័យកម្ពុជា', 'Full tuition scholarship for students from rural poor backgrounds with GPA 3.5+.', 'អាហារូបករណ៍ថ្លៃសិក្សាទាំងស្រុងសម្រាប់សិស្សពីគ្រួសារក្រីក្រជនបទ មាន GPA ៣.៥+។', 'full', 'Full tuition + internship opportunities', 'ថ្លៃសិក្សាទាំងស្រុង + ឱកាសកម្មសិក្សា', 'Rural poor students, GPA 3.5+', 'សិស្សក្រីក្រជនបទ មាន GPA ៣.៥+', NULL, NULL, true),
('22222222-2222-2222-2222-222222222225', 'PUC Scholarship', 'អាហារូបករណ៍សាកលវិទ្យាល័យ បញ្ញាសាស្ត្រ (PUC)', 'Pannasastra University of Cambodia', 'សាកលវិទ្យាល័យបញ្ញាសាស្ត្រកម្ពុជា', 'GPA-linked sliding scale scholarship for low-income students after completing first semester with B average or above.', 'អាហារូបករណ៍ផ្អែកលើ GPA សម្រាប់សិស្សមានចំណូលទាប បន្ទាប់ពីបញ្ចប់ឆមាសទី ១ ដោយមានមធ្យមភាគ B ឡើង។', 'partial', 'Full to partial tuition (GPA-linked sliding scale)', 'ថ្លៃសិក្សាទាំងស្រុង ដល់ផ្នែក (ផ្អែកលើ GPA)', 'After first semester, B average or above, low-income', 'បន្ទាប់ពីឆមាសទី ១ មធ្យមភាគ B ឡើង ចំណូលទាប', NULL, NULL, true),
('22222222-2222-2222-2222-222222222226', 'Singapore ASEAN Scholarship', 'អាហារូបករណ៍ ASEAN សិង្ហបុរី', 'Singapore Ministry of Education (MOE)', 'ក្រសួងអប់រំសិង្ហបុរី (MOE)', 'Study in Singapore from Secondary 3 through GCE A-levels at a selected secondary school.', 'សិក្សានៅសិង្ហបុរីពី Secondary 3 ដល់ GCE A-levels នៅសាលាមធ្យមសិក្សាដែលបានជ្រើសរើស។', 'full', 'Full tuition + annual allowance + return airfare + health insurance', 'ថ្លៃសិក្សាទាំងស្រុង + ប្រាក់ឧបត្ថម្ភប្រចាំឆ្នាំ + សំបុត្រយន្តហោះទៅមក + ធានារ៉ាប់រងសុខភាព', 'Completed grade 10 (born Jan 2, 2009 - Jan 1, 2012), strong English required', 'បញ្ចប់ថ្នាក់ទី ១០ (កើត ២ មករា ២០០៩ - ១ មករា ២០១២) ត្រូវការអង់គ្លេសកម្រិតខ្ពស់', NULL, '2026-05-31', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO scholarships (id, name_en, name_km, provider_en, provider_km, description_en, description_km, type, coverage_en, coverage_km, eligibility_en, eligibility_km, application_url, deadline, is_active) VALUES
('22222222-2222-2222-2222-222222222227', 'UWCSEA 5-Year Scholarship (Singapore)', 'អាហារូបករណ៍ ៥ ឆ្នាំ UWCSEA (សិង្ហបុរី)', 'UWC Cambodia National Committee', 'គណៈកម្មាធិការជាតិ UWC កម្ពុជា', 'Full scholarship for 2 Cambodian students (ages 13-15) to study IB Diploma at UWCSEA Singapore.', 'អាហារូបករណ៍ពេញសម្រាប់សិស្សកម្ពុជា ២ នាក់ (អាយុ ១៣-១៥ឆ្នាំ) ដើម្បីសិក្សា IB Diploma នៅ UWCSEA សិង្ហបុរី។', 'full', 'Full tuition, boarding, meals, return airfare (fully funded)', 'ថ្លៃសិក្សា បន្ទប់គេង អាហារ សំបុត្រយន្តហោះទៅមក (ផ្តល់មូលនិធិពេញ)', 'Cambodian nationals ages 13-15', 'ពលរដ្ឋខ្មែរអាយុ ១៣-១៥ឆ្នាំ', NULL, NULL, true),
('22222222-2222-2222-2222-222222222228', 'UWC 2-Year Scholarship (18 countries)', 'អាហារូបករណ៍ ២ ឆ្នាំ UWC (១៨ ប្រទេស)', 'UWC Cambodia National Committee', 'គណៈកម្មាធិការជាតិ UWC កម្ពុជា', 'Scholarship to study 2-year IB Diploma at one of 18 UWC schools worldwide.', 'អាហារូបករណ៍សិក្សា IB Diploma ២ ឆ្នាំនៅសាលា UWC មួយក្នុងចំណោម ១៨ សាលាទូទាំងពិភពលោក។', 'full', 'Full to partial (80%+ receive full or substantial funding)', 'ពេញ ដល់ ផ្នែក (៨០%+ ទទួលបានមូលនិធិពេញ ឬច្រើន)', 'Ages 16-18 (grades 11-12), deadline Nov 15 each year', 'អាយុ ១៦-១៨ឆ្នាំ (ថ្នាក់ទី ១១-១២) ផុតកំណត់ ១៥ វិច្ឆិកាជារៀងរាល់ឆ្នាំ', NULL, '2026-11-15', true),
('22222222-2222-2222-2222-222222222229', 'Asia Kakehashi Project+ (Japan)', 'គម្រោងស្ពានអាស៊ី+ (ជប៉ុន)', 'MEXT x AFS', 'ក្រសួងអប់រំជប៉ុន x AFS', 'One-year exchange program at a Japanese public high school with homestay. Fully funded.', 'កម្មវិធីផ្លាស់ប្តូរមួយឆ្នាំនៅវិទ្យាល័យសាធារណៈជប៉ុន ជាមួយគ្រួសារជប៉ុន។ ផ្តល់មូលនិធិពេញ។', 'full', 'Return airfare, tuition, homestay, living expenses (fully funded)', 'សំបុត្រយន្តហោះទៅមក ថ្លៃសិក្សា គ្រួសារជប៉ុន ការចំណាយរស់នៅ (ផ្តល់មូលនិធិពេញ)', 'Ages 15-18 (current high school students), Japanese not required', 'អាយុ ១៥-១៨ឆ្នាំ (សិស្សវិទ្យាល័យបច្ចុប្បន្ន) មិនចាំបាច់ចេះភាសាជប៉ុន', NULL, '2026-01-31', true),
('22222222-2222-2222-2222-222222222230', 'Korean GKS Scholarship (Undergraduate)', 'អាហារូបករណ៍ GKS កូរ៉េ (បរិញ្ញាបត្រ)', 'NIIED (Korea)', 'NIIED (កូរ៉េ)', 'Full scholarship to study undergraduate degree in South Korea for 5 years including 1 year Korean language training.', 'អាហារូបករណ៍ពេញដើម្បីសិក្សាបរិញ្ញាបត្រនៅកូរ៉េខាងត្បូង ៥ ឆ្នាំ រួមទាំងបណ្តុះបណ្តាលភាសាកូរ៉េ ១ ឆ្នាំ។', 'full', '800,000 KRW/month (~$600) + full tuition + return airfare', '៨០០,០០០ វ៉ុន/ខែ (~$៦០០) + ថ្លៃសិក្សាទាំងស្រុង + សំបុត្រយន្តហោះទៅមក', 'High school graduates (under 25), Korean not required', 'និស្សិតបញ្ចប់វិទ្យាល័យ (អាយុក្រោម ២៥ឆ្នាំ) មិនចាំបាច់ចេះកូរ៉េ', NULL, '2026-03-31', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO scholarships (id, name_en, name_km, provider_en, provider_km, description_en, description_km, type, coverage_en, coverage_km, eligibility_en, eligibility_km, application_url, deadline, is_active) VALUES
('22222222-2222-2222-2222-222222222231', 'China CSC Scholarship (Undergraduate)', 'អាហារូបករណ៍ CSC ចិន (បរិញ្ញាបត្រ)', 'Chinese Government (CSC)', 'រដ្ឋាភិបាលចិន (CSC)', 'Full scholarship to study at Chinese universities for 4-5 years across all fields.', 'អាហារូបករណ៍ពេញដើម្បីសិក្សានៅសាកលវិទ្យាល័យចិន ៤-៥ ឆ្នាំ គ្រប់វិស័យ។', 'full', '2,500 CNY/month (~$350) + full tuition + dormitory + insurance', '២,៥០០ យ៉ន់/ខែ (~$៣៥០) + ថ្លៃសិក្សាទាំងស្រុង + បន្ទប់គេង + ធានារ៉ាប់រង', 'High school graduates, Chinese not required (training provided)', 'និស្សិតបញ្ចប់វិទ្យាល័យ មិនចាំបាច់ចេះចិន (មានបណ្តុះបណ្តាល)', NULL, '2026-04-30', true),
('22222222-2222-2222-2222-222222222232', 'Stipendium Hungaricum (Hungary)', 'អាហារូបករណ៍ Stipendium Hungaricum (ហុងគ្រី)', 'Hungarian Government (Tempus Foundation)', 'រដ្ឋាភិបាលហុងគ្រី (មូលនិធិ Tempus)', 'Scholarship to study at 29 Hungarian universities with 600+ programs. MoEYS nomination required.', 'អាហារូបករណ៍សិក្សានៅសាកលវិទ្យាល័យហុងគ្រី ២៩ ជាមួយកម្មវិធី ៦០០+។ ត្រូវការការតែងតាំង MoEYS។', 'full', 'Full tuition + 43,700 HUF/month (~110 EUR) + dormitory + insurance', 'ថ្លៃសិក្សាទាំងស្រុង + ៤៣,៧០០ HUF/ខែ (~១១០ EUR) + បន្ទប់គេង + ធានារ៉ាប់រង', 'High school graduates (18+), nominated through MoEYS', 'និស្សិតបញ្ចប់វិទ្យាល័យ (១៨ឆ្នាំ+) តែងតាំងតាមរយៈ MoEYS', NULL, '2026-01-15', true),
('22222222-2222-2222-2222-222222222233', 'MoEYS Bilateral Scholarships (Various Countries)', 'អាហារូបករណ៍ទ្វេភាគី MoEYS (ប្រទេសផ្សេងៗ)', 'MoEYS (bilateral agreements)', 'ក្រសួងអប់រំ (កិច្ចព្រមព្រៀងទ្វេភាគី)', 'Scholarships through bilateral agreements with Turkey, Russia, India, Taiwan, Vietnam, and other countries.', 'អាហារូបករណ៍តាមរយៈកិច្ចព្រមព្រៀងទ្វេភាគីជាមួយទួរគី រុស្ស៊ី ឥណ្ឌា តៃវ៉ាន់ វៀតណាម និងប្រទេសផ្សេងៗ។', 'full', 'Varies by country (most are fully funded)', 'ខុសគ្នាតាមប្រទេស (ភាគច្រើនផ្តល់មូលនិធិពេញ)', 'High school graduates, selected through MoEYS', 'និស្សិតបញ្ចប់វិទ្យាល័យ ជ្រើសរើសតាមរយៈ MoEYS', NULL, NULL, true)
ON CONFLICT (id) DO NOTHING;

-- New scholarship-university relations
INSERT INTO scholarship_university_relations (scholarship_id, university_id) VALUES
('22222222-2222-2222-2222-222222222207', '11111111-1111-1111-1111-111111111101'),
('22222222-2222-2222-2222-222222222207', '11111111-1111-1111-1111-111111111102'),
('22222222-2222-2222-2222-222222222208', '11111111-1111-1111-1111-111111111102'),
('22222222-2222-2222-2222-222222222208', '11111111-1111-1111-1111-111111111101'),
('22222222-2222-2222-2222-222222222208', '11111111-1111-1111-1111-111111111104'),
('22222222-2222-2222-2222-222222222219', '11111111-1111-1111-1111-111111111101'),
('22222222-2222-2222-2222-222222222219', '11111111-1111-1111-1111-111111111102'),
('22222222-2222-2222-2222-222222222221', '11111111-1111-1111-1111-111111111104'),
('22222222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111104'),
('22222222-2222-2222-2222-222222222223', '11111111-1111-1111-1111-111111111104')
ON CONFLICT DO NOTHING;
