-- Additions from Scholarships_additions.xlsx (2026-07-24)
-- 8 new scholarships not already present in the scholarships table.
-- NOTE: Khmer (_km) text is a draft translation and should be reviewed by a
-- native speaker before publishing (see translation-checker agent).
-- Skipped from the source file: 7 duplicates of existing rows, 2 ambiguous
-- entries needing clarification, and 5 "Others" entries with insufficient
-- detail (see conversation for the full breakdown).

INSERT INTO scholarships (id, name_en, name_km, provider_en, provider_km, description_en, description_km, type, coverage_en, coverage_km, eligibility_en, eligibility_km, application_url, deadline, is_domestic, is_active) VALUES
('22222222-2222-2222-2222-222222222234', 'CSC ASEAN (AUN) Program', 'អាហារូបករណ៍ CSC កម្មវិធី ASEAN (AUN)', 'China Scholarship Council', 'ក្រុមប្រឹក្សាអាហារូបករណ៍ចិន (CSC)', 'Graduate-level scholarship for ASEAN nationals to study at CSC-designated Chinese universities through the ASEAN University Network (AUN) program.', 'អាហារូបករណ៍កម្រិតឧត្តមសិក្សាសម្រាប់ពលរដ្ឋប្រទេស ASEAN ដើម្បីសិក្សានៅសាកលវិទ្យាល័យចិនដែលបានកំណត់ តាមរយៈកម្មវិធីបណ្តាញសាកលវិទ្យាល័យ ASEAN (AUN)។', 'full', 'Full tuition (details vary by university)', 'ថ្លៃសិក្សាទាំងស្រុង (ខុសគ្នាតាមសាកលវិទ្យាល័យ)', 'ASEAN nationals, graduate-level applicants, admission through designated universities only', 'ពលរដ្ឋប្រទេស ASEAN និស្សិតកម្រិតឧត្តមសិក្សា ចូលរៀនតាមរយៈសាកលវិទ្យាល័យដែលបានកំណត់តែប៉ុណ្ណោះ', 'https://www.campuschina.org', NULL, true, true),
('22222222-2222-2222-2222-222222222235', 'Chelly Foundation Scholarship', 'អាហារូបករណ៍មូលនិធិ Chelly', 'Chelly Foundation (NGO)', 'មូលនិធិ Chelly (អង្គការក្រៅរដ្ឋាភិបាល)', 'Full or partial tuition scholarship for young women to study at universities in Phnom Penh; can be combined with the Harpswell Foundation scholarship.', 'អាហារូបករណ៍ថ្លៃសិក្សាទាំងស្រុង ឬដោយផ្នែក សម្រាប់ស្ត្រីវ័យក្មេងសិក្សានៅសាកលវិទ្យាល័យក្នុងភ្នំពេញ អាចផ្សំជាមួយអាហារូបករណ៍មូលនិធិ Harpswell បាន។', 'partial', 'Full or partial tuition, depending on selection', 'ថ្លៃសិក្សាទាំងស្រុង ឬដោយផ្នែក អាស្រ័យលើការជ្រើសរើស', 'Female students at universities in Phnom Penh', 'សិស្សនិស្សិតស្រីនៅសាកលវិទ្យាល័យក្នុងភ្នំពេញ', 'https://www.globalgiving.org/projects/college-scholarships-for-young-women-in-cambodia/', NULL, true, true),
('22222222-2222-2222-2222-222222222236', 'Cambodian Scholarship Foundation (CASF) Scholarship', 'អាហារូបករណ៍មូលនិធិអាហារូបករណ៍កម្ពុជា (CASF)', 'Cambodian Scholarship Foundation / Open Book Libraries (NGO)', 'មូលនិធិអាហារូបករណ៍កម្ពុជា / Open Book Libraries (អង្គការក្រៅរដ្ឋាភិបាល)', 'Full scholarship for students from Kandal and Svay Rieng provinces, covering secondary school through university, including dormitory, living expenses, tuition, and mentoring.', 'អាហារូបករណ៍ពេញសម្រាប់សិស្សនិស្សិតមកពីខេត្តកណ្តាល និងស្វាយរៀង គ្របដណ្តប់ពីមធ្យមសិក្សាដល់សាកលវិទ្យាល័យ រួមមានបន្ទប់គេង ការចំណាយរស់នៅ ថ្លៃសិក្សា និងការណែនាំ។', 'full', 'Dormitory, living expenses, tuition, and mentoring', 'បន្ទប់គេង ការចំណាយរស់នៅ ថ្លៃសិក្សា និងការណែនាំ', 'Students from Kandal and Svay Rieng provinces (high school through university)', 'សិស្សនិស្សិតមកពីខេត្តកណ្តាល និងស្វាយរៀង (ពីវិទ្យាល័យដល់សាកលវិទ្យាល័យ)', 'http://www.cambodianscholarship.org/', NULL, true, true),
('22222222-2222-2222-2222-222222222237', 'Chevening Scholarship', 'អាហារូបករណ៍ Chevening', 'UK Embassy / FCDO', 'ស្ថានទូតអង់គ្លេស / FCDO', 'Full scholarship for a one-year master''s degree at any of 150+ UK universities, aimed at future leaders with relevant professional work experience. Applications typically open in early November each year.', 'អាហារូបករណ៍ពេញសម្រាប់សញ្ញាបត្របរិញ្ញាបត្រជាន់ខ្ពស់រយៈពេល ១ ឆ្នាំ នៅសាកលវិទ្យាល័យអង់គ្លេសជាង ១៥០ សម្រាប់អ្នកដឹកនាំអនាគតដែលមានបទពិសោធន៍ការងារពាក់ព័ន្ធ។ ដាក់ពាក្យធម្មតាបើកនៅដើមខែវិច្ឆិកាជារៀងរាល់ឆ្នាំ។', 'full', 'Full tuition, living expenses, and travel costs for a 1-year master''s program', 'ថ្លៃសិក្សាទាំងស្រុង ការចំណាយរស់នៅ និងសំបុត្រធ្វើដំណើរ សម្រាប់កម្មវិធីបរិញ្ញាបត្រជាន់ខ្ពស់ ១ ឆ្នាំ', 'Requires relevant professional work experience; graduate-level (1-year master''s) applicants', 'ត្រូវការបទពិសោធន៍ការងារពាក់ព័ន្ធ សម្រាប់អ្នកដាក់ពាក្យកម្រិតឧត្តមសិក្សា (បរិញ្ញាបត្រជាន់ខ្ពស់ ១ ឆ្នាំ)', 'https://www.chevening.org/scholarship/cambodia/', NULL, true, true),
('22222222-2222-2222-2222-222222222238', 'Manaaki New Zealand Scholarships', 'អាហារូបករណ៍ Manaaki នូវែលសេឡង់', 'NZ Ministry of Foreign Affairs and Trade (MFAT) / NZ Embassy (via IDP)', 'ក្រសួងការបរទេស និងពាណិជ្ជកម្មនូវែលសេឡង់ (MFAT) / ស្ថានទូតនូវែលសេឡង់ (តាមរយៈ IDP)', 'Full scholarship for graduate study in New Zealand for candidates with relevant work experience, with around 35 places available annually in fields such as climate, disaster resilience, agriculture, energy, governance, and TESOL. Applications typically close in late February.', 'អាហារូបករណ៍ពេញសម្រាប់ការសិក្សាកម្រិតឧត្តមសិក្សានៅនូវែលសេឡង់ សម្រាប់អ្នកមានបទពិសោធន៍ការងារពាក់ព័ន្ធ មានកន្លែងប្រមាណ ៣៥ ក្នុងមួយឆ្នាំ ក្នុងវិស័យអាកាសធាតុ គ្រោះមហន្តរាយ កសិកម្ម ថាមពល អភិបាលកិច្ច និង TESOL។ ដាក់ពាក្យធម្មតាបិទនៅចុងខែកុម្ភៈ។', 'full', 'Full tuition, living expenses, and travel costs for graduate study', 'ថ្លៃសិក្សាទាំងស្រុង ការចំណាយរស់នៅ និងសំបុត្រធ្វើដំណើរ សម្រាប់ការសិក្សាកម្រិតឧត្តមសិក្សា', 'Requires relevant work experience; approximately 35 places per year in priority fields (climate, disaster risk, agriculture, energy, governance, TESOL)', 'ត្រូវការបទពិសោធន៍ការងារពាក់ព័ន្ធ មានកន្លែងប្រមាណ ៣៥ ក្នុងមួយឆ្នាំ ក្នុងវិស័យអាទិភាព', 'https://www.nzscholarships.govt.nz', NULL, true, true),
('22222222-2222-2222-2222-222222222239', 'DAAD EPOS Scholarship', 'អាហារូបករណ៍ DAAD EPOS', 'DAAD (German Academic Exchange Service)', 'DAAD (សេវាផ្លាស់ប្តូរសិក្សាអាហារូបករណ៍អាល្លឺម៉ង់)', 'Full scholarship for graduate study at DAAD EPOS-affiliated programs in Germany, requiring at least 2 years of relevant professional experience.', 'អាហារូបករណ៍ពេញសម្រាប់ការសិក្សាកម្រិតឧត្តមសិក្សានៅកម្មវិធីដែលពាក់ព័ន្ធនឹង DAAD EPOS នៅអាល្លឺម៉ង់ ត្រូវការបទពិសោធន៍ការងារពាក់ព័ន្ធយ៉ាងតិច ២ ឆ្នាំ។', 'full', 'Full tuition, monthly stipend, and travel costs', 'ថ្លៃសិក្សាទាំងស្រុង ប្រាក់ឧបត្ថម្ភប្រចាំខែ និងសំបុត្រធ្វើដំណើរ', 'Requires at least 2 years of relevant professional work experience; graduate-level applicants', 'ត្រូវការបទពិសោធន៍ការងារពាក់ព័ន្ធយ៉ាងតិច ២ ឆ្នាំ សម្រាប់អ្នកដាក់ពាក្យកម្រិតឧត្តមសិក្សា', 'https://www.daad.de/en/', NULL, true, true),
('22222222-2222-2222-2222-222222222240', 'DAAD STEM Scholarship (CLMV Program)', 'អាហារូបករណ៍ DAAD STEM (កម្មវិធី CLMV)', 'DAAD (German Academic Exchange Service)', 'DAAD (សេវាផ្លាស់ប្តូរសិក្សាអាហារូបករណ៍អាល្លឺម៉ង់)', 'Graduate scholarship in STEM fields at German universities, limited to applicants from Cambodia, Laos, Myanmar, and Vietnam (CLMV countries).', 'អាហារូបករណ៍កម្រិតឧត្តមសិក្សាក្នុងវិស័យ STEM នៅសាកលវិទ្យាល័យអាល្លឺម៉ង់ សម្រាប់តែអ្នកដាក់ពាក្យមកពីកម្ពុជា ឡាវ មីយ៉ាន់ម៉ា និងវៀតណាម (ប្រទេស CLMV)។', 'full', 'Full tuition and stipend (details vary by program)', 'ថ្លៃសិក្សាទាំងស្រុង និងប្រាក់ឧបត្ថម្ភ (ខុសគ្នាតាមកម្មវិធី)', 'Nationals of Cambodia, Laos, Myanmar, or Vietnam; graduate-level STEM applicants', 'ពលរដ្ឋកម្ពុជា ឡាវ មីយ៉ាន់ម៉ា ឬវៀតណាម សម្រាប់អ្នកដាក់ពាក្យកម្រិតឧត្តមសិក្សាវិស័យ STEM', 'https://www.daad-vietnam.org/en/find-funding/', NULL, true, true),
('22222222-2222-2222-2222-222222222241', 'Erasmus Mundus Joint Master Degrees', 'សញ្ញាបត្របរិញ្ញាបត្រជាន់ខ្ពស់រួម Erasmus Mundus', 'European Union / Erasmus+', 'សហភាពអឺរ៉ុប / Erasmus+', 'Full scholarship for joint master''s programs delivered across two or more European universities, funded by the EU''s Erasmus+ program.', 'អាហារូបករណ៍ពេញសម្រាប់កម្មវិធីបរិញ្ញាបត្រជាន់ខ្ពស់រួម ដែលបង្រៀននៅសាកលវិទ្យាល័យអឺរ៉ុបចាប់ពី ២ ឡើងទៅ ផ្តល់មូលនិធិដោយកម្មវិធី Erasmus+ របស់សហភាពអឺរ៉ុប។', 'full', 'Full tuition, living allowance, and travel costs (varies by program)', 'ថ្លៃសិក្សាទាំងស្រុង ប្រាក់ឧបត្ថម្ភរស់នៅ និងសំបុត្រធ្វើដំណើរ (ខុសគ្នាតាមកម្មវិធី)', 'Open to all nationalities; admission requirements vary by joint master''s program', 'បើកចំហសម្រាប់សញ្ជាតិទាំងអស់ លក្ខខណ្ឌចូលរៀនខុសគ្នាតាមកម្មវិធី', 'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters', NULL, true, true)
ON CONFLICT (id) DO NOTHING;
