export type CareerCategory = "realistic" | "high-income" | "social-impact";

export type FilterKey =
  | "highDemand"
  | "remotePossible"
  | "growthIndustry"
  | "universityRequired"
  | "vocationalPossible";

export type EducationLevel = "vocational" | "bachelor" | "master" | "any";

export type InterestType = "people" | "technology" | "money" | "social";

export interface SkillDetail {
  name: { en: string; km: string };
  level: 1 | 2 | 3 | 4 | 5; // proficiency required
}

export interface CareerPathStep {
  titleEn: string;
  titleKm: string;
  yearsEn: string;
  yearsKm: string;
  salaryEn: string;
  salaryKm: string;
}

export interface CareerDetail {
  taglineEn: string;
  taglineKm: string;
  jobDescriptionEn: string;
  jobDescriptionKm: string;
  dailyTasksEn: string[];
  dailyTasksKm: string[];
  detailedSkills: SkillDetail[];
  incomeIntlMin: number;
  incomeIntlMax: number;
  educationPathEn: string;
  educationPathKm: string;
  selfTaughtPossible: boolean;
  cambodiaDetailEn: string;
  cambodiaDetailKm: string;
  internationalDetailEn: string;
  internationalDetailKm: string;
  remotePossible: boolean;
  growthExplanationEn: string;
  growthExplanationKm: string;
  careerPath: CareerPathStep[];
  relatedPrograms: string[];
  relatedFields: string[];
}

export interface Career {
  id: string;
  nameEn: string;
  nameKm: string;
  descriptionEn: string;
  descriptionKm: string;
  image: string; // path to career photo
  category: CareerCategory;
  skills: { en: string; km: string }[];
  incomeMin: number; // USD monthly
  incomeMax: number;
  educationLevel: EducationLevel;
  cambodiaAvailable: boolean;
  internationalAvailable: boolean;
  growthScore: number; // 1-5
  filters: FilterKey[];
  interestTypes: InterestType[];
  englishRequired: "none" | "basic" | "intermediate" | "advanced";
  skillDifficulty: 1 | 2 | 3 | 4 | 5;
  detail: CareerDetail;
}

export const CAREERS: Career[] = [
  // ─── Realistic & Accessible ───
  {
    id: "accounting-assistant",
    nameEn: "Accounting Assistant",
    nameKm: "ជំនួយការគណនេយ្យ",
    descriptionEn: "Support businesses with bookkeeping, invoices, and financial records.",
    descriptionKm: "ជួយគ្រប់គ្រងសៀវភៅគណនេយ្យ វិក្កយបត្រ និងកំណត់ត្រាហិរញ្ញវត្ថុ។",
    image: "/images/careers/accounting.jpg",
    category: "realistic",
    skills: [
      { en: "Excel", km: "Excel" },
      { en: "Bookkeeping", km: "គណនេយ្យ" },
      { en: "Detail-oriented", km: "យកចិត្តទុកដាក់" },
    ],
    incomeMin: 250,
    incomeMax: 500,
    educationLevel: "vocational",
    cambodiaAvailable: true,
    internationalAvailable: false,
    growthScore: 3,
    filters: ["highDemand", "vocationalPossible"],
    interestTypes: ["money"],
    englishRequired: "basic",
    skillDifficulty: 2,
    detail: {
      taglineEn: "Keep businesses running with numbers",
      taglineKm: "គ្រប់គ្រងលេខដើម្បីឱ្យអាជីវកម្មដំណើរការ",
      jobDescriptionEn: "Record financial transactions, manage invoices, reconcile accounts, and prepare basic financial reports for small and medium businesses.",
      jobDescriptionKm: "កត់ត្រាប្រតិបត្តិការហិរញ្ញវត្ថុ គ្រប់គ្រងវិក្កយបត្រ ផ្ទៀងផ្ទាត់គណនី និងរៀបចំរបាយការណ៍ហិរញ្ញវត្ថុមូលដ្ឋាន។",
      dailyTasksEn: ["Enter transactions into accounting software", "Process invoices and receipts", "Reconcile bank statements", "Prepare monthly reports"],
      dailyTasksKm: ["បញ្ចូលប្រតិបត្តិការទៅក្នុងកម្មវិធីគណនេយ្យ", "ដំណើរការវិក្កយបត្រ និងបង្កាន់ដៃ", "ផ្ទៀងផ្ទាត់របាយការណ៍ធនាគារ", "រៀបចំរបាយការណ៍ប្រចាំខែ"],
      detailedSkills: [
        { name: { en: "Excel / Spreadsheets", km: "Excel / សៀវភៅបញ្ជី" }, level: 4 },
        { name: { en: "Bookkeeping", km: "គណនេយ្យសៀវភៅ" }, level: 3 },
        { name: { en: "Attention to Detail", km: "ការយកចិត្តទុកដាក់លម្អិត" }, level: 4 },
        { name: { en: "QuickBooks / Accounting Software", km: "កម្មវិធីគណនេយ្យ" }, level: 3 },
      ],
      incomeIntlMin: 800,
      incomeIntlMax: 2000,
      educationPathEn: "Vocational certificate in accounting or associate degree. Bachelor's in accounting opens more doors.",
      educationPathKm: "វិញ្ញាបនបត្រវិជ្ជាជីវៈផ្នែកគណនេយ្យ ឬសញ្ញាបត្រអនុបណ្ឌិត។ បរិញ្ញាបត្រគណនេយ្យបើកឱកាសកាន់តែច្រើន។",
      selfTaughtPossible: true,
      cambodiaDetailEn: "High demand in Phnom Penh, Siem Reap, and Battambang. Every business needs accounting support.",
      cambodiaDetailKm: "តម្រូវការខ្ពស់នៅភ្នំពេញ សៀមរាប និងបាត់ដំបង។ គ្រប់អាជីវកម្មត្រូវការជំនួយគណនេយ្យ។",
      internationalDetailEn: "Limited international mobility without higher qualifications.",
      internationalDetailKm: "ឱកាសក្រៅប្រទេសមានកម្រិត បើគ្មានគុណវុឌ្ឍិខ្ពស់។",
      remotePossible: false,
      growthExplanationEn: "Steady demand as Cambodia's business sector grows. Automation may change some tasks but human oversight remains essential.",
      growthExplanationKm: "តម្រូវការមានស្ថិរភាពដោយសារវិស័យអាជីវកម្មកម្ពុជាកំពុងរីកចម្រើន។",
      careerPath: [
        { titleEn: "Junior Assistant", titleKm: "ជំនួយការក្មេង", yearsEn: "0-1 yr", yearsKm: "០-១ ឆ្នាំ", salaryEn: "$200-300", salaryKm: "$200-300" },
        { titleEn: "Accounting Assistant", titleKm: "ជំនួយការគណនេយ្យ", yearsEn: "1-3 yrs", yearsKm: "១-៣ ឆ្នាំ", salaryEn: "$300-500", salaryKm: "$300-500" },
        { titleEn: "Senior Accountant", titleKm: "គណនេយ្យករជាន់ខ្ពស់", yearsEn: "3-7 yrs", yearsKm: "៣-៧ ឆ្នាំ", salaryEn: "$500-1000", salaryKm: "$500-1000" },
      ],
      relatedPrograms: ["Business / Management", "IT / Computer Science"],
      relatedFields: ["Business", "Information Technology"],
    },
  },
  {
    id: "hospitality-staff",
    nameEn: "Hospitality & Hotel Staff",
    nameKm: "បុគ្គលិកសណ្ឋាគារ និងបដិសណ្ឋារកិច្ច",
    descriptionEn: "Work in hotels, resorts, and restaurants serving local and international guests.",
    descriptionKm: "ធ្វើការនៅសណ្ឋាគារ រមណីយដ្ឋាន និងភោជនីយដ្ឋាន បម្រើភ្ញៀវក្នុង និងក្រៅប្រទេស។",
    image: "/images/careers/hospitality.jpg",
    category: "realistic",
    skills: [
      { en: "Customer Service", km: "សេវាអតិថិជន" },
      { en: "Communication", km: "ទំនាក់ទំនង" },
      { en: "Teamwork", km: "ការងារក្រុម" },
    ],
    incomeMin: 200,
    incomeMax: 600,
    educationLevel: "vocational",
    cambodiaAvailable: true,
    internationalAvailable: true,
    growthScore: 4,
    filters: ["highDemand", "vocationalPossible", "growthIndustry"],
    interestTypes: ["people"],
    englishRequired: "intermediate",
    skillDifficulty: 2,
    detail: {
      taglineEn: "Create unforgettable guest experiences",
      taglineKm: "បង្កើតបទពិសោធន៍ដែលមិនអាចបំភ្លេចបានសម្រាប់ភ្ញៀវ",
      jobDescriptionEn: "Welcome guests, manage front desk operations, coordinate with housekeeping and F&B teams, and ensure guest satisfaction at hotels and resorts.",
      jobDescriptionKm: "ស្វាគមន៍ភ្ញៀវ គ្រប់គ្រងប្រតិបត្តិការផ្នែកទទួលភ្ញៀវ សម្របសម្រួលជាមួយក្រុមផ្សេងៗ និងធានាថាភ្ញៀវពេញចិត្ត។",
      dailyTasksEn: ["Check in and check out guests", "Handle reservations and inquiries", "Coordinate with housekeeping", "Resolve guest complaints"],
      dailyTasksKm: ["ទទួលភ្ញៀវចូល និងចេញ", "គ្រប់គ្រងការកក់ និងសំណួរ", "សម្របសម្រួលជាមួយផ្នែកសម្អាត", "ដោះស្រាយពាក្យបណ្តឹងភ្ញៀវ"],
      detailedSkills: [
        { name: { en: "Customer Service", km: "សេវាអតិថិជន" }, level: 5 },
        { name: { en: "English Communication", km: "ទំនាក់ទំនងជាភាសាអង់គ្លេស" }, level: 3 },
        { name: { en: "Teamwork", km: "ការងារក្រុម" }, level: 4 },
        { name: { en: "Problem Solving", km: "ដោះស្រាយបញ្ហា" }, level: 3 },
      ],
      incomeIntlMin: 1000,
      incomeIntlMax: 3000,
      educationPathEn: "Vocational training in hospitality (4-12 months). A degree in Tourism/Hospitality Management opens management roles.",
      educationPathKm: "វគ្គបណ្តុះបណ្តាលវិជ្ជាជីវៈផ្នែកបដិសណ្ឋារកិច្ច (៤-១២ ខែ)។ សញ្ញាបត្រគ្រប់គ្រងទេសចរណ៍បើកឱកាសគ្រប់គ្រង។",
      selfTaughtPossible: false,
      cambodiaDetailEn: "Booming tourism industry — Siem Reap, Phnom Penh, Sihanoukville, Kep have strong demand year-round.",
      cambodiaDetailKm: "ឧស្សាហកម្មទេសចរណ៍កំពុងរីកចម្រើន — សៀមរាប ភ្នំពេញ ព្រះសីហនុ កែប មានតម្រូវការខ្ពស់ពេញមួយឆ្នាំ។",
      internationalDetailEn: "Strong international demand. Experience in Cambodia's luxury resorts is valued globally.",
      internationalDetailKm: "តម្រូវការអន្តរជាតិខ្ពស់។ បទពិសោធន៍នៅរមណីយដ្ឋានប្រណីតកម្ពុជាមានតម្លៃទូទាំងពិភពលោក។",
      remotePossible: false,
      growthExplanationEn: "Cambodia targets 7M+ tourists. Hotels, resorts, and restaurants are expanding fast across the country.",
      growthExplanationKm: "កម្ពុជាកំណត់គោលដៅទេសចរ ៧លាន+។ សណ្ឋាគារ រមណីយដ្ឋាន និងភោជនីយដ្ឋានកំពុងពង្រីកយ៉ាងឆាប់រហ័ស។",
      careerPath: [
        { titleEn: "Trainee / Intern", titleKm: "សិក្ខាកាម", yearsEn: "0-1 yr", yearsKm: "០-១ ឆ្នាំ", salaryEn: "$150-250", salaryKm: "$150-250" },
        { titleEn: "Front Desk / F&B Staff", titleKm: "បុគ្គលិកទទួលភ្ញៀវ", yearsEn: "1-3 yrs", yearsKm: "១-៣ ឆ្នាំ", salaryEn: "$250-500", salaryKm: "$250-500" },
        { titleEn: "Supervisor / Manager", titleKm: "អ្នកគ្រប់គ្រង", yearsEn: "3-7 yrs", yearsKm: "៣-៧ ឆ្នាំ", salaryEn: "$500-1200", salaryKm: "$500-1200" },
      ],
      relatedPrograms: ["Tourism / Hospitality"],
      relatedFields: ["Hospitality & Tourism"],
    },
  },
  {
    id: "construction-technician",
    nameEn: "Construction Technician",
    nameKm: "ជាងបច្ចេកទេorg សំណង់",
    descriptionEn: "Build and maintain structures — electrical, plumbing, and structural work.",
    descriptionKm: "សាងសង់ និងថែទាំអគារ — ការងារអគ្គិសនី ទឹក និងរចនាសម្ព័ន្ធ។",
    image: "/images/careers/construction.jpg",
    category: "realistic",
    skills: [
      { en: "Technical Skills", km: "ជំនាញបច្ចេកទេស" },
      { en: "Safety", km: "សុវត្ថិភាព" },
      { en: "Blueprint Reading", km: "អានប្លង់" },
    ],
    incomeMin: 300,
    incomeMax: 700,
    educationLevel: "vocational",
    cambodiaAvailable: true,
    internationalAvailable: false,
    growthScore: 4,
    filters: ["highDemand", "vocationalPossible", "growthIndustry"],
    interestTypes: ["technology"],
    englishRequired: "none",
    skillDifficulty: 3,
    detail: {
      taglineEn: "Build Cambodia's future — literally",
      taglineKm: "សាងសង់អនាគតកម្ពុជា — ពិតជាទៅ",
      jobDescriptionEn: "Install electrical wiring, plumbing systems, and structural elements in residential and commercial buildings. Read blueprints and ensure safety standards.",
      jobDescriptionKm: "ដំឡើងខ្សែអគ្គិសនី ប្រព័ន្ធទឹក និងរចនាសម្ព័ន្ធក្នុងអគារលំនៅដ្ឋាន និងពាណិជ្ជកម្ម។ អានប្លង់ និងធានាស្តង់ដារសុវត្ថិភាព។",
      dailyTasksEn: ["Read construction blueprints", "Install electrical or plumbing systems", "Inspect work quality and safety", "Coordinate with construction team"],
      dailyTasksKm: ["អានប្លង់សំណង់", "ដំឡើងប្រព័ន្ធអគ្គិសនី ឬទឹក", "ពិនិត្យគុណភាព និងសុវត្ថិភាព", "សម្របសម្រួលជាមួយក្រុមសំណង់"],
      detailedSkills: [
        { name: { en: "Electrical Wiring", km: "ខ្សែអគ្គិសនី" }, level: 4 },
        { name: { en: "Blueprint Reading", km: "ការអានប្លង់" }, level: 3 },
        { name: { en: "Safety Standards", km: "ស្តង់ដារសុវត្ថិភាព" }, level: 4 },
        { name: { en: "Physical Fitness", km: "សមត្ថភាពរាងកាយ" }, level: 3 },
      ],
      incomeIntlMin: 1500,
      incomeIntlMax: 4000,
      educationPathEn: "Vocational training (4-12 months) at NPIC, NTTI, or PTC. No university required.",
      educationPathKm: "បណ្តុះបណ្តាលវិជ្ជាជីវៈ (៤-១២ ខែ) នៅ NPIC, NTTI ឬ PTC។ មិនតម្រូវសាកលវិទ្យាល័យ។",
      selfTaughtPossible: false,
      cambodiaDetailEn: "Construction boom across Cambodia. Massive demand in Phnom Penh, Sihanoukville, and new development zones.",
      cambodiaDetailKm: "វិស័យសំណង់កំពុងរីកដុះដាលទូទាំងកម្ពុជា។ តម្រូវការច្រើននៅភ្នំពេញ ព្រះសីហនុ និងតំបន់អភិវឌ្ឍន៍ថ្មី។",
      internationalDetailEn: "Skilled technicians can find work in neighboring countries (Thailand, Vietnam) or the Gulf states.",
      internationalDetailKm: "ជាងបច្ចេកទេorg ជំនាញអាចរកការងារនៅប្រទេសជិតខាង (ថៃ វៀតណាម) ឬរដ្ឋឈូងសមុទ្រ។",
      remotePossible: false,
      growthExplanationEn: "Cambodia's $3B+ construction sector is one of the fastest growing in ASEAN. Skilled technicians are in short supply.",
      growthExplanationKm: "វិស័យសំណង់កម្ពុជាដែលមានតម្លៃ $៣ពាន់លាន+ គឺជាមួយក្នុងចំណោមវិស័យរីកចម្រើនលឿនបំផុតក្នុងអាស៊ាន។",
      careerPath: [
        { titleEn: "Apprentice", titleKm: "សិស្សហ្វឹកហាត់", yearsEn: "0-1 yr", yearsKm: "០-១ ឆ្នាំ", salaryEn: "$200-300", salaryKm: "$200-300" },
        { titleEn: "Technician", titleKm: "ជាងបច្ចេកទorg org", yearsEn: "1-3 yrs", yearsKm: "១-៣ ឆ្នាំ", salaryEn: "$300-600", salaryKm: "$300-600" },
        { titleEn: "Senior Tech / Foreman", titleKm: "ជាងជាន់ខ្ពស់ / មេការ", yearsEn: "3-8 yrs", yearsKm: "៣-៨ ឆ្នាំ", salaryEn: "$600-1200", salaryKm: "$600-1200" },
      ],
      relatedPrograms: ["Engineering"],
      relatedFields: ["Engineering"],
    },
  },
  {
    id: "teacher",
    nameEn: "Teacher",
    nameKm: "គ្រូបង្រៀន",
    descriptionEn: "Educate the next generation in schools across Cambodia.",
    descriptionKm: "បង្រៀនមេរៀនដល់កុមារគ្រប់សាលានៅទូទាំងកម្ពុជា។",
    image: "/images/careers/teacher.jpg",
    category: "realistic",
    skills: [
      { en: "Teaching", km: "ការបង្រៀន" },
      { en: "Patience", km: "ការអត់ធ្មត់" },
      { en: "Communication", km: "ទំនាក់ទំនង" },
    ],
    incomeMin: 200,
    incomeMax: 500,
    educationLevel: "bachelor",
    cambodiaAvailable: true,
    internationalAvailable: false,
    growthScore: 3,
    filters: ["highDemand", "universityRequired"],
    interestTypes: ["people", "social"],
    englishRequired: "basic",
    skillDifficulty: 3,
    detail: {
      taglineEn: "Shape the next generation of Cambodia",
      taglineKm: "បង្កើតជំនាន់បន្ទាប់នៃកម្ពុជា",
      jobDescriptionEn: "Plan and deliver lessons, assess student progress, mentor young learners, and contribute to curriculum development in schools across Cambodia.",
      jobDescriptionKm: "រៀបចំ និងបង្រៀនមេរៀន វាយតម្លៃវឌ្ឍនភាពសិស្ស ណែនាំសិស្ស និងចូលរួមអភិវឌ្ឍកម្មវិធីសិក្សា។",
      dailyTasksEn: ["Prepare and deliver lessons", "Grade assignments and exams", "Meet with parents", "Develop teaching materials"],
      dailyTasksKm: ["រៀបចំ និងបង្រៀនមេរៀន", "ដាក់ពិន្ទុកិច្ចការ និងប្រឡង", "ជួបជាមួយឪពុកម្តាយ", "បង្កើតសម្ភារៈបង្រៀន"],
      detailedSkills: [
        { name: { en: "Lesson Planning", km: "រៀបចំមេរៀន" }, level: 4 },
        { name: { en: "Communication", km: "ទំនាក់ទំនង" }, level: 5 },
        { name: { en: "Patience", km: "ការអត់ធ្មត់" }, level: 5 },
        { name: { en: "Subject Knowledge", km: "ចំណេះដឹងមុខវិជ្ជា" }, level: 4 },
      ],
      incomeIntlMin: 1500,
      incomeIntlMax: 4000,
      educationPathEn: "Bachelor's degree in Education required for public schools. Private schools may accept relevant experience.",
      educationPathKm: "បរិញ្ញាបត្រអប់រំតម្រូវសម្រាប់សាលារដ្ឋ។ សាលាឯកជនអាចទទួលយកបទពិសោធន៍ពាក់ព័ន្ធ។",
      selfTaughtPossible: false,
      cambodiaDetailEn: "Government and private schools across all 25 provinces. English teachers are especially in demand.",
      cambodiaDetailKm: "សាលារដ្ឋ និងឯកជនទូទាំង ២៥ រាជធានី-ខេត្ត។ គ្រូបង្រៀនភាសាអង់គ្លេសមានតម្រូវការខ្ពស់ជាពិសេស។",
      internationalDetailEn: "Limited without international teaching certifications.",
      internationalDetailKm: "មានកម្រិត បើគ្មានវិញ្ញាបនបត្របង្រៀនអន្តរជាតិ។",
      remotePossible: false,
      growthExplanationEn: "Cambodia investing heavily in education. Teacher salaries improving but slowly. Stable long-term career.",
      growthExplanationKm: "កម្ពុជាកំពុងវិនិយោគយ៉ាងច្រើនក្នុងវិស័យអប់រំ។ ប្រាក់ខែគ្រូកំពុងកែលម្អ។ អាជីពមានស្ថិរភាពរយៈពេលវែង។",
      careerPath: [
        { titleEn: "Student Teacher", titleKm: "គ្រូសិក្ខាកាម", yearsEn: "0-1 yr", yearsKm: "០-១ ឆ្នាំ", salaryEn: "$150-250", salaryKm: "$150-250" },
        { titleEn: "Teacher", titleKm: "គ្រូបង្រៀន", yearsEn: "1-5 yrs", yearsKm: "១-៥ ឆ្នាំ", salaryEn: "$250-500", salaryKm: "$250-500" },
        { titleEn: "Senior / Head Teacher", titleKm: "គ្រូជាន់ខ្ពស់", yearsEn: "5-10 yrs", yearsKm: "៥-១០ ឆ្នាំ", salaryEn: "$400-800", salaryKm: "$400-800" },
      ],
      relatedPrograms: ["Education / Teaching"],
      relatedFields: ["Education"],
    },
  },

  // ─── High-Income & Growth Industries ───
  {
    id: "software-developer",
    nameEn: "Software Developer",
    nameKm: "អ្នកអភិវឌ្ឍន៍កម្មវិធី",
    descriptionEn: "Build web and mobile applications for local and global companies.",
    descriptionKm: "បង្កើតកម្មវិធីគេហទំព័រ និងទូរស័ព្ទសម្រាប់ក្រុមហ៊ុនក្នុង និងក្រៅប្រទេស។",
    image: "/images/careers/software-dev.jpg",
    category: "high-income",
    skills: [
      { en: "JavaScript", km: "JavaScript" },
      { en: "Problem Solving", km: "ដោះស្រាយបញ្ហា" },
      { en: "Git", km: "Git" },
    ],
    incomeMin: 500,
    incomeMax: 2500,
    educationLevel: "any",
    cambodiaAvailable: true,
    internationalAvailable: true,
    growthScore: 5,
    filters: [
      "highDemand",
      "remotePossible",
      "growthIndustry",
      "vocationalPossible",
    ],
    interestTypes: ["technology", "money"],
    englishRequired: "intermediate",
    skillDifficulty: 4,
    detail: {
      taglineEn: "Build apps that change lives",
      taglineKm: "បង្កើតកម្មវិធីដែលផ្លាស់ប្តូរជីវិត",
      jobDescriptionEn: "Design, code, test, and deploy web and mobile applications. Work with teams to build products used by thousands.",
      jobDescriptionKm: "រចនា សរសេរកូដ សាកល្បង និងដាក់ឱ្យដំណើរការកម្មវិធីគេហទំព័រ និងទូរស័ព្ទ។",
      dailyTasksEn: ["Write and review code", "Fix bugs and optimize performance", "Collaborate with designers and PMs", "Deploy and monitor applications"],
      dailyTasksKm: ["សរសេរ និងពិនិត្យកូដ", "ជួសជុលកំហុស និងបង្កើនប្រសិទ្ធភាព", "សហការជាមួយអ្នករចនា និង PM", "ដាក់ឱ្យដំណើរការ និងតាមដានកម្មវិធី"],
      detailedSkills: [
        { name: { en: "JavaScript / TypeScript", km: "JavaScript / TypeScript" }, level: 5 },
        { name: { en: "React / Next.js", km: "React / Next.js" }, level: 4 },
        { name: { en: "Problem Solving", km: "ដោះស្រាយបញ្ហា" }, level: 5 },
        { name: { en: "Git & DevOps", km: "Git & DevOps" }, level: 3 },
      ],
      incomeIntlMin: 3000, incomeIntlMax: 10000,
      educationPathEn: "University degree in CS recommended but self-taught developers are widely accepted. Bootcamps and online courses work too.",
      educationPathKm: "សញ្ញាបត្រវិទ្យាសាស្ត្រកុំព្យូទ័រត្រូវបានណែនាំ ប៉ុន្តែអ្នកអភិវឌ្ឍន៍រៀនដោយខ្លួនឯងត្រូវបានទទួលយកយ៉ាងទូលំទូលាយ។",
      selfTaughtPossible: true,
      cambodiaDetailEn: "Growing tech scene in Phnom Penh. Startups, agencies, and international companies hiring actively.",
      cambodiaDetailKm: "វិស័យបច្ចេកវិទ្យាកំពុងរីកចម្រើននៅភ្នំពេញ។ ស្តាតអាព់ ទីភ្នាក់ងារ និងក្រុមហ៊ុនអន្តរជាតិកំពុងជ្រើសរើសយ៉ាងសកម្ម។",
      internationalDetailEn: "One of the most globally mobile careers. Remote work for US/EU companies pays $3,000-$10,000+/month.",
      internationalDetailKm: "ជាអាជីពមួយដែលមានចលនាអន្តរជាតិខ្ពស់បំផុត។ ការងារពីចម្ងាយសម្រាប់ក្រុមហ៊ុន US/EU បង់ $៣,០០០-$១០,០០០+/ខែ។",
      remotePossible: true,
      growthExplanationEn: "Software demand is exploding globally. AI is creating new roles, not replacing developers. Cambodia's tech sector growing 20%+ annually.",
      growthExplanationKm: "តម្រូវការកម្មវិធីកំពុងផ្ទុះទូទាំងពិភពលោក។ AI កំពុងបង្កើតតួនាទីថ្មី មិនមែនជំនួសអ្នកអភិវឌ្ឍន៍។",
      careerPath: [
        { titleEn: "Junior Developer", titleKm: "អ្នកអភិវឌ្ឍន៍ក្មេង", yearsEn: "0-2 yrs", yearsKm: "០-២ ឆ្នាំ", salaryEn: "$400-800", salaryKm: "$400-800" },
        { titleEn: "Mid Developer", titleKm: "អ្នកអភិវឌ្ឍន៍មធ្យម", yearsEn: "2-5 yrs", yearsKm: "២-៥ ឆ្នាំ", salaryEn: "$800-1800", salaryKm: "$800-1800" },
        { titleEn: "Senior / Lead", titleKm: "ជាន់ខ្ពស់ / អ្នកដឹកនាំ", yearsEn: "5+ yrs", yearsKm: "៥+ ឆ្នាំ", salaryEn: "$1800-4000+", salaryKm: "$1800-4000+" },
      ],
      relatedPrograms: ["IT / Computer Science", "Engineering"],
      relatedFields: ["Information Technology"],
    },
  },
  {
    id: "digital-marketer",
    nameEn: "Digital Marketer",
    nameKm: "អ្នកទីផ្សារឌីជីថល",
    descriptionEn: "Run social media, ads, and online campaigns for businesses.",
    descriptionKm: "គ្រប់គ្រងបណ្តាញសង្គម ការផ្សាយពាណិជ្ជកម្ម និងយុទ្ធនាការអនឡាញ។",
    image: "/images/careers/digital-marketing.jpg",
    category: "high-income",
    skills: [
      { en: "Social Media", km: "បណ្តាញសង្គម" },
      { en: "Analytics", km: "ការវិភាគ" },
      { en: "Content Creation", km: "បង្កើតខ្លឹមសារ" },
    ],
    incomeMin: 400,
    incomeMax: 1500,
    educationLevel: "any",
    cambodiaAvailable: true,
    internationalAvailable: true,
    growthScore: 5,
    filters: ["highDemand", "remotePossible", "growthIndustry", "vocationalPossible"],
    interestTypes: ["money", "technology"],
    englishRequired: "intermediate",
    skillDifficulty: 3,
    detail: {
      taglineEn: "Turn clicks into customers",
      taglineKm: "ប្រែក្លាយការចុចទៅជាអតិថិជន",
      jobDescriptionEn: "Plan and execute digital marketing campaigns across social media, search engines, and email. Analyze data to optimize results.",
      jobDescriptionKm: "រៀបចំ និងអនុវត្តយុទ្ធនាការទីផ្សារឌីជីថលតាមបណ្តាញសង្គម ម៉ាស៊ីនស្វែងរក និងអ៊ីមែល។",
      dailyTasksEn: ["Create social media content", "Manage ad campaigns (Facebook, Google)", "Analyze campaign performance", "Write copy and plan content calendars"],
      dailyTasksKm: ["បង្កើតខ្លឹមសារបណ្តាញសង្គម", "គ្រប់គ្រងយុទ្ធនាការផ្សាយពាណិជ្ជកម្ម", "វិភាគប្រសិទ្ធភាពយុទ្ធនាការ", "សរសេរខ្លឹមសារ និងរៀបចំប្រតិទិន"],
      detailedSkills: [
        { name: { en: "Social Media Marketing", km: "ទីផ្សារបណ្តាញសង្គម" }, level: 5 },
        { name: { en: "Google/Facebook Ads", km: "ការផ្សាយពាណិជ្ជកម្ម" }, level: 4 },
        { name: { en: "Analytics & Data", km: "ការវិភាគទិន្នន័យ" }, level: 3 },
        { name: { en: "Content Writing", km: "សរសេរខ្លឹមសារ" }, level: 4 },
      ],
      incomeIntlMin: 2000, incomeIntlMax: 7000,
      educationPathEn: "No formal degree required. Online certifications (Google, Meta) are highly valued. A business degree helps.",
      educationPathKm: "មិនតម្រូវសញ្ញាបត្រផ្លូវការ។ វិញ្ញាបនបត្រអនឡាញ (Google, Meta) មានតម្លៃខ្ពស់។",
      selfTaughtPossible: true,
      cambodiaDetailEn: "Every business in Cambodia needs digital marketing. Facebook is the #1 platform — huge demand for FB specialists.",
      cambodiaDetailKm: "គ្រប់អាជីវកម្មក្នុងកម្ពុជាត្រូវការទីផ្សារឌីជីថល។ Facebook ជាវេទិកា #១ — តម្រូវការច្រើនសម្រាប់អ្នកជំនាញ FB។",
      internationalDetailEn: "Fully remote-capable. Freelancing for international clients is very common.",
      internationalDetailKm: "អាចធ្វើការពីចម្ងាយបានពេញលេញ។ ធ្វើការឯករាជ្យសម្រាប់អតិថិជនអន្តរជាតិពេញនិយមខ្លាំង។",
      remotePossible: true,
      growthExplanationEn: "Digital ad spending growing 25%+ yearly in Cambodia. Every new business needs online presence.",
      growthExplanationKm: "ការចំណាយលើផ្សាយពាណិជ្ជកម្មឌីជីថលកើន ២៥%+ ប្រចាំឆ្នាំក្នុងកម្ពុជា។",
      careerPath: [
        { titleEn: "Junior Marketer", titleKm: "អ្នកទីផ្សារក្មេង", yearsEn: "0-1 yr", yearsKm: "០-១ ឆ្នាំ", salaryEn: "$300-500", salaryKm: "$300-500" },
        { titleEn: "Digital Marketer", titleKm: "អ្នកទីផ្សារឌីជីថល", yearsEn: "1-3 yrs", yearsKm: "១-៣ ឆ្នាំ", salaryEn: "$500-1000", salaryKm: "$500-1000" },
        { titleEn: "Marketing Manager", titleKm: "អ្នកគ្រប់គ្រងទីផ្សារ", yearsEn: "3-6 yrs", yearsKm: "៣-៦ ឆ្នាំ", salaryEn: "$1000-2500", salaryKm: "$1000-2500" },
      ],
      relatedPrograms: ["Business / Management", "IT / Computer Science"],
      relatedFields: ["Business", "Information Technology"],
    },
  },
  {
    id: "ui-ux-designer",
    nameEn: "UI/UX Designer",
    nameKm: "អ្នករចនា UI/UX",
    descriptionEn: "Design user interfaces and experiences for apps and websites.",
    descriptionKm: "រចនាចំណុចប្រទាក់ និងបទពិសោធន៍អ្នកប្រើប្រាស់សម្រាប់កម្មវិធី និងគេហទំព័រ។",
    image: "/images/careers/ui-ux.jpg",
    category: "high-income",
    skills: [
      { en: "Figma", km: "Figma" },
      { en: "Design Thinking", km: "ការគិតរចនា" },
      { en: "Prototyping", km: "Prototyping" },
    ],
    incomeMin: 500,
    incomeMax: 2000,
    educationLevel: "any",
    cambodiaAvailable: true,
    internationalAvailable: true,
    growthScore: 5,
    filters: ["remotePossible", "growthIndustry", "vocationalPossible"],
    interestTypes: ["technology"],
    englishRequired: "intermediate",
    skillDifficulty: 3,
    detail: {
      taglineEn: "Design experiences people love",
      taglineKm: "រចនាបទពិសោធន៍ដែលមនុស្សស្រឡាញ់",
      jobDescriptionEn: "Research user needs, create wireframes and prototypes, design beautiful interfaces, and test usability for apps and websites.",
      jobDescriptionKm: "ស្រាវជ្រាវតម្រូវការអ្នកប្រើប្រាស់ បង្កើត wireframe និង prototype រចនាចំណុចប្រទាក់ស្រស់ស្អាត។",
      dailyTasksEn: ["Research user behavior", "Create wireframes in Figma", "Design UI components", "Run usability tests"],
      dailyTasksKm: ["ស្រាវជ្រាវអាកប្បកិរិយាអ្នកប្រើ", "បង្កើត wireframe ក្នុង Figma", "រចនា UI components", "ធ្វើតេស្តភាពងាយស្រួលប្រើ"],
      detailedSkills: [
        { name: { en: "Figma / Design Tools", km: "Figma / ឧបករណ៍រចនា" }, level: 5 },
        { name: { en: "Design Thinking", km: "ការគិតរចនា" }, level: 4 },
        { name: { en: "User Research", km: "ស្រាវជ្រាវអ្នកប្រើ" }, level: 3 },
        { name: { en: "Visual Design", km: "រចនាសោភ័ណ" }, level: 5 },
      ],
      incomeIntlMin: 3000, incomeIntlMax: 8000,
      educationPathEn: "No degree required. Portfolio matters most. Online courses and bootcamps are effective paths.",
      educationPathKm: "មិនតម្រូវសញ្ញាបត្រ។ ផលប័ត្រសំខាន់បំផុត។ វគ្គអនឡាញ និង bootcamp ជាផ្លូវប្រសិទ្ធ។",
      selfTaughtPossible: true,
      cambodiaDetailEn: "Growing demand from tech startups and digital agencies in Phnom Penh.",
      cambodiaDetailKm: "តម្រូវការកើនឡើងពី tech startup និងទីភ្នាក់ងារឌីជីថលនៅភ្នំពេញ។",
      internationalDetailEn: "Highly remote-friendly. Designers can work for global companies from Cambodia.",
      internationalDetailKm: "ងាយស្រួលធ្វើការពីចម្ងាយ។ អ្នករចនាអាចធ្វើការសម្រាប់ក្រុមហ៊ុនពិភពលោកពីកម្ពុជា។",
      remotePossible: true,
      growthExplanationEn: "Every digital product needs UI/UX. Demand outpaces supply globally. AI tools enhance designers rather than replace them.",
      growthExplanationKm: "ផលិតផលឌីជីថលគ្រប់យ៉ាងត្រូវការ UI/UX។ តម្រូវការលើសពីការផ្គត់ផ្គង់ជាសកល។",
      careerPath: [
        { titleEn: "Junior Designer", titleKm: "អ្នករចនាក្មេង", yearsEn: "0-2 yrs", yearsKm: "០-២ ឆ្នាំ", salaryEn: "$400-700", salaryKm: "$400-700" },
        { titleEn: "UI/UX Designer", titleKm: "អ្នករចនា UI/UX", yearsEn: "2-5 yrs", yearsKm: "២-៥ ឆ្នាំ", salaryEn: "$700-1500", salaryKm: "$700-1500" },
        { titleEn: "Senior / Design Lead", titleKm: "ជាន់ខ្ពស់ / អ្នកដឹកនាំរចនា", yearsEn: "5+ yrs", yearsKm: "៥+ ឆ្នាំ", salaryEn: "$1500-3000+", salaryKm: "$1500-3000+" },
      ],
      relatedPrograms: ["Arts / Design", "IT / Computer Science"],
      relatedFields: ["Arts & Design", "Information Technology"],
    },
  },
  {
    id: "finance-banking",
    nameEn: "Finance & Banking",
    nameKm: "ហិរញ្ញវត្ថុ និងធនាគារ",
    descriptionEn: "Work in banks, microfinance, or investment firms managing money.",
    descriptionKm: "ធ្វើការនៅធនាគារ មីក្រូហិរញ្ញវត្ថុ ឬក្រុមហ៊ុនវិនិយោគ។",
    image: "/images/careers/finance.jpg",
    category: "high-income",
    skills: [
      { en: "Financial Analysis", km: "វិភាគហិរញ្ញវត្ថុ" },
      { en: "Excel", km: "Excel" },
      { en: "Risk Assessment", km: "វាយតម្លៃហានិភ័យ" },
    ],
    incomeMin: 400,
    incomeMax: 2000,
    educationLevel: "bachelor",
    cambodiaAvailable: true,
    internationalAvailable: true,
    growthScore: 4,
    filters: ["highDemand", "growthIndustry", "universityRequired"],
    interestTypes: ["money"],
    englishRequired: "intermediate",
    skillDifficulty: 4,
    detail: {
      taglineEn: "Manage money, build wealth",
      taglineKm: "គ្រប់គ្រងប្រាក់ កសាងទ្រព្យសម្បត្តិ",
      jobDescriptionEn: "Analyze financial data, manage loans and investments, assess risks, and help clients grow their wealth at banks and financial institutions.",
      jobDescriptionKm: "វិភាគទិន្នន័យហិរញ្ញវត្ថុ គ្រប់គ្រងកម្ចី និងវិនិយោគ វាយតម្លៃហានិភ័យ។",
      dailyTasksEn: ["Analyze financial statements", "Process loan applications", "Meet with clients", "Prepare risk reports"],
      dailyTasksKm: ["វិភាគរបាយការណ៍ហិរញ្ញវត្ថុ", "ដំណើរការពាក្យសុំកម្ចី", "ជួបជាមួយអតិថិជន", "រៀបចំរបាយការណ៍ហានិភ័យ"],
      detailedSkills: [
        { name: { en: "Financial Analysis", km: "វិភាគហិរញ្ញវត្ថុ" }, level: 5 },
        { name: { en: "Excel / Financial Modeling", km: "Excel / គំរូហិរញ្ញវត្ថុ" }, level: 4 },
        { name: { en: "Risk Assessment", km: "វាយតម្លៃហានិភ័យ" }, level: 4 },
        { name: { en: "Communication", km: "ទំនាក់ទំនង" }, level: 3 },
      ],
      incomeIntlMin: 3000, incomeIntlMax: 10000,
      educationPathEn: "Bachelor's in Finance, Accounting, or Business required. MBA or CFA opens senior roles.",
      educationPathKm: "បរិញ្ញាបត្រហិរញ្ញវត្ថុ គណនេយ្យ ឬពាណិជ្ជសាស្ត្រតម្រូវ។ MBA ឬ CFA បើកមុខតំណែងជាន់ខ្ពស់។",
      selfTaughtPossible: false,
      cambodiaDetailEn: "70+ banks and 80+ microfinance institutions. One of the fastest-growing financial sectors in ASEAN.",
      cambodiaDetailKm: "ធនាគារ ៧០+ និងគ្រឹះស្ថានមីក្រូហិរញ្ញវត្ថុ ៨០+។ វិស័យហិរញ្ញវត្ថុរីកចម្រើនលឿនបំផុតមួយក្នុងអាស៊ាន។",
      internationalDetailEn: "Strong international opportunities with the right qualifications. Singapore and Bangkok are regional hubs.",
      internationalDetailKm: "ឱកាសអន្តរជាតិរឹងមាំជាមួយគុណវុឌ្ឍិត្រឹមត្រូវ។ សិង្ហបុរី និងបាងកកជាមជ្ឈមណ្ឌលក្នុងតំបន់។",
      remotePossible: false,
      growthExplanationEn: "Cambodia's banking sector grows 15-20% annually. Fintech is creating new roles. Microfinance expanding to rural areas.",
      growthExplanationKm: "វិស័យធនាគារកម្ពុជារីកចម្រើន ១៥-២០% ប្រចាំឆ្នាំ។ Fintech កំពុងបង្កើតតួនាទីថ្មី។",
      careerPath: [
        { titleEn: "Junior Analyst / Teller", titleKm: "អ្នកវិភាគក្មេង", yearsEn: "0-2 yrs", yearsKm: "០-២ ឆ្នាំ", salaryEn: "$350-600", salaryKm: "$350-600" },
        { titleEn: "Officer / Analyst", titleKm: "មន្រ្តី / អ្នកវិភាគ", yearsEn: "2-5 yrs", yearsKm: "២-៥ ឆ្នាំ", salaryEn: "$600-1200", salaryKm: "$600-1200" },
        { titleEn: "Manager / Senior", titleKm: "អ្នកគ្រប់គ្រង / ជាន់ខ្ពស់", yearsEn: "5+ yrs", yearsKm: "៥+ ឆ្នាំ", salaryEn: "$1200-3000+", salaryKm: "$1200-3000+" },
      ],
      relatedPrograms: ["Business / Management"],
      relatedFields: ["Business"],
    },
  },

  // ─── Social Impact Careers ───
  {
    id: "ngo-project-manager",
    nameEn: "NGO Project Manager",
    nameKm: "អ្នកគ្រប់គ្រងគម្រោង NGO",
    descriptionEn: "Lead development projects that improve communities across Cambodia.",
    descriptionKm: "ដឹកនាំគម្រោងអភិវឌ្ឍន៍ដែលកែលម្អសហគមន៍នៅទូទាំងកម្ពុជា។",
    image: "/images/careers/ngo.jpg",
    category: "social-impact",
    skills: [
      { en: "Project Management", km: "គ្រប់គ្រងគម្រោង" },
      { en: "Leadership", km: "ភាពជាអ្នកដឹកនាំ" },
      { en: "Report Writing", km: "សរសេររបាយការណ៍" },
    ],
    incomeMin: 500,
    incomeMax: 1500,
    educationLevel: "bachelor",
    cambodiaAvailable: true,
    internationalAvailable: true,
    growthScore: 3,
    filters: ["highDemand", "universityRequired"],
    interestTypes: ["people", "social"],
    englishRequired: "advanced",
    skillDifficulty: 4,
    detail: {
      taglineEn: "Lead projects that change communities",
      taglineKm: "ដឹកនាំគម្រោងដែលផ្លាស់ប្តូរសហគមន៍",
      jobDescriptionEn: "Plan, execute, and monitor development projects for NGOs. Manage budgets, coordinate with stakeholders, and write reports for donors.",
      jobDescriptionKm: "រៀបចំ អនុវត្ត និងតាមដានគម្រោងអភិវឌ្ឍន៍សម្រាប់ NGO។ គ្រប់គ្រងថវិកា សម្របសម្រួលជាមួយភាគីពាក់ព័ន្ធ។",
      dailyTasksEn: ["Plan project activities and timelines", "Manage budgets and procurement", "Write donor reports", "Visit field sites and communities"],
      dailyTasksKm: ["រៀបចំសកម្មភាព និងកាលវិភាគគម្រោង", "គ្រប់គ្រងថវិកា", "សរសេររបាយការណ៍ជូនម្ចាស់ជំនួយ", "ចុះទស្សនាការដ្ឋាន និងសហគមន៍"],
      detailedSkills: [
        { name: { en: "Project Management", km: "គ្រប់គ្រងគម្រោង" }, level: 5 },
        { name: { en: "Report Writing (English)", km: "សរសេររបាយការណ៍ (អង់គ្លេស)" }, level: 5 },
        { name: { en: "Budget Management", km: "គ្រប់គ្រងថវិកា" }, level: 4 },
        { name: { en: "Leadership", km: "ភាពជាអ្នកដឹកនាំ" }, level: 4 },
      ],
      incomeIntlMin: 2000, incomeIntlMax: 6000,
      educationPathEn: "Bachelor's in Social Science, Development Studies, or related field. Master's preferred for senior roles.",
      educationPathKm: "បរិញ្ញាបត្រវិទ្យាសាស្ត្រសង្គម ឬអភិវឌ្ឍន៍សិក្សា។ អនុបណ្ឌិតត្រូវបានគេពេញចិត្តសម្រាប់មុខតំណែងជាន់ខ្ពស់។",
      selfTaughtPossible: false,
      cambodiaDetailEn: "Hundreds of NGOs operate in Cambodia. Phnom Penh is the hub, but field work spans all provinces.",
      cambodiaDetailKm: "អង្គការ NGO រាប់រយកំពុងប្រតិបត្តិការក្នុងកម្ពុជា។ ភ្នំពេញជាមជ្ឈមណ្ឌល ប៉ុន្តែការងារវាលគ្របដណ្តប់គ្រប់ខេត្ត។",
      internationalDetailEn: "Strong international mobility. UN agencies, INGOs, and development banks hire globally.",
      internationalDetailKm: "ចលនាអន្តរជាតិរឹងមាំ។ ទីភ្នាក់ងារ UN, INGO និងធនាគារអភិវឌ្ឍន៍ជ្រើសរើសជាសកល។",
      remotePossible: false,
      growthExplanationEn: "Aid sector shifting but still strong in Cambodia. Climate adaptation and digital inclusion creating new project areas.",
      growthExplanationKm: "វិស័យជំនួយកំពុងផ្លាស់ប្តូរ ប៉ុន្តែនៅតែរឹងមាំក្នុងកម្ពុជា។",
      careerPath: [
        { titleEn: "Project Assistant", titleKm: "ជំនួយការគម្រោង", yearsEn: "0-2 yrs", yearsKm: "០-២ ឆ្នាំ", salaryEn: "$400-700", salaryKm: "$400-700" },
        { titleEn: "Project Officer", titleKm: "មន្រ្តីគម្រោង", yearsEn: "2-5 yrs", yearsKm: "២-៥ ឆ្នាំ", salaryEn: "$700-1200", salaryKm: "$700-1200" },
        { titleEn: "Project Manager", titleKm: "អ្នកគ្រប់គ្រងគម្រោង", yearsEn: "5+ yrs", yearsKm: "៥+ ឆ្នាំ", salaryEn: "$1200-2500+", salaryKm: "$1200-2500+" },
      ],
      relatedPrograms: ["Social Science", "Business / Management"],
      relatedFields: ["Social Science"],
    },
  },
  {
    id: "healthcare-worker",
    nameEn: "Healthcare Worker",
    nameKm: "បុគ្គលិកសុខាភិបាល",
    descriptionEn: "Provide medical care and health education in communities.",
    descriptionKm: "ផ្តល់ការថែទាំសុខភាព និងការអប់រំសុខភាពក្នុងសហគមន៍។",
    image: "/images/careers/healthcare.jpg",
    category: "social-impact",
    skills: [
      { en: "Medical Knowledge", km: "ចំណេះដឹងវេជ្ជសាស្ត្រ" },
      { en: "Empathy", km: "ការយល់ចិត្ត" },
      { en: "First Aid", km: "សង្គ្រោះបឋម" },
    ],
    incomeMin: 300,
    incomeMax: 1200,
    educationLevel: "bachelor",
    cambodiaAvailable: true,
    internationalAvailable: true,
    growthScore: 4,
    filters: ["highDemand", "universityRequired", "growthIndustry"],
    interestTypes: ["people", "social"],
    englishRequired: "basic",
    skillDifficulty: 5,
    detail: {
      taglineEn: "Heal people, save lives",
      taglineKm: "ព្យាបាលមនុស្ស រក្សាជីវិត",
      jobDescriptionEn: "Provide medical care, health screenings, vaccinations, and health education in hospitals, clinics, and rural communities.",
      jobDescriptionKm: "ផ្តល់ការថែទាំវេជ្ជសាស្ត្រ ការពិនិត្យសុខភាព ការចាក់វ៉ាក់សាំង និងការអប់រំសុខភាពក្នុងមន្ទីរពេទ្យ គ្លីនិក និងសហគមន៍ជនបទ។",
      dailyTasksEn: ["Examine and treat patients", "Administer medications", "Conduct health education sessions", "Record patient data"],
      dailyTasksKm: ["ពិនិត្យ និងព្យាបាលអ្នកជំងឺ", "ផ្តល់ឱសថ", "ធ្វើវគ្គអប់រំសុខភាព", "កត់ត្រាទិន្នន័យអ្នកជំងឺ"],
      detailedSkills: [
        { name: { en: "Clinical Skills", km: "ជំនាញគ្លីនិក" }, level: 5 },
        { name: { en: "Empathy & Care", km: "ការយល់ចិត្ត និងថែទាំ" }, level: 5 },
        { name: { en: "Medical Knowledge", km: "ចំណេះដឹងវេជ្ជសាស្ត្រ" }, level: 5 },
        { name: { en: "First Aid", km: "សង្គ្រោះបឋម" }, level: 4 },
      ],
      incomeIntlMin: 2000, incomeIntlMax: 6000,
      educationPathEn: "Bachelor's in Nursing, Public Health, or Medicine required. Specialized training for different roles.",
      educationPathKm: "បរិញ្ញាបត្រផ្នែកគិលានុបដ្ឋាក សុខភាពសាធារណៈ ឬវេជ្ជសាស្ត្រតម្រូវ។",
      selfTaughtPossible: false,
      cambodiaDetailEn: "Severe shortage of healthcare workers, especially in rural areas. Government actively recruiting.",
      cambodiaDetailKm: "កង្វះធ្ងន់ធ្ងរនៃបុគ្គលិកសុខាភិបាល ជាពិសេសក្នុងតំបន់ជនបទ។ រដ្ឋាភិបាលកំពុងជ្រើសរើសយ៉ាងសកម្ម។",
      internationalDetailEn: "Nurses and health workers are in demand globally. Additional certifications may be needed.",
      internationalDetailKm: "គិលានុបដ្ឋាក និងបុគ្គលិកសុខភាពមានតម្រូវការជាសកល។ វិញ្ញាបនបត្របន្ថែមអាចចាំបាច់។",
      remotePossible: false,
      growthExplanationEn: "Cambodia expanding healthcare access nationwide. Post-COVID investment in public health continues to grow.",
      growthExplanationKm: "កម្ពុជាកំពុងពង្រីកការទទួលបានសេវាសុខាភិបាលទូទាំងប្រទេស។",
      careerPath: [
        { titleEn: "Health Assistant", titleKm: "ជំនួយការសុខភាព", yearsEn: "0-2 yrs", yearsKm: "០-២ ឆ្នាំ", salaryEn: "$250-400", salaryKm: "$250-400" },
        { titleEn: "Nurse / Health Officer", titleKm: "គិលានុបដ្ឋាក / មន្រ្តីសុខភាព", yearsEn: "2-5 yrs", yearsKm: "២-៥ ឆ្នាំ", salaryEn: "$400-800", salaryKm: "$400-800" },
        { titleEn: "Senior / Specialist", titleKm: "ជាន់ខ្ពស់ / អ្នកឯកទេស", yearsEn: "5+ yrs", yearsKm: "៥+ ឆ្នាំ", salaryEn: "$800-1500+", salaryKm: "$800-1500+" },
      ],
      relatedPrograms: ["Medicine / Health"],
      relatedFields: ["Healthcare"],
    },
  },
  {
    id: "social-worker",
    nameEn: "Social Worker",
    nameKm: "បុគ្គលិកសង្គមកិច្ច",
    descriptionEn: "Help vulnerable people access services, education, and support.",
    descriptionKm: "ជួយមនុស្សងាយរងគ្រោះឱ្យទទួលបានសេវា ការអប់រំ និងការគាំទ្រ។",
    image: "/images/careers/social-work.jpg",
    category: "social-impact",
    skills: [
      { en: "Counseling", km: "ការប្រឹក្សា" },
      { en: "Empathy", km: "ការយល់ចិត្ត" },
      { en: "Community Work", km: "ការងារសហគមន៍" },
    ],
    incomeMin: 250,
    incomeMax: 800,
    educationLevel: "bachelor",
    cambodiaAvailable: true,
    internationalAvailable: false,
    growthScore: 3,
    filters: ["highDemand", "universityRequired"],
    interestTypes: ["people", "social"],
    englishRequired: "basic",
    skillDifficulty: 3,
    detail: {
      taglineEn: "Protect the most vulnerable",
      taglineKm: "ការពារអ្នកដែលងាយរងគ្រោះបំផុត",
      jobDescriptionEn: "Support vulnerable individuals and families — children, elderly, disabled — by connecting them to services, counseling, and community resources.",
      jobDescriptionKm: "គាំទ្របុគ្គល និងគ្រួសារងាយរងគ្រោះ — កុមារ មនុស្សចាស់ ជនពិការ — ដោយភ្ជាប់ពួកគេទៅសេវា ការប្រឹក្សា និងធនធានសហគមន៍។",
      dailyTasksEn: ["Conduct home visits", "Assess family needs", "Connect clients to services", "Write case reports"],
      dailyTasksKm: ["ចុះទស្សនាផ្ទះ", "វាយតម្លៃតម្រូវការគ្រួសារ", "ភ្ជាប់អតិថិជនទៅសេវា", "សរសេររបាយការណ៍ករណី"],
      detailedSkills: [
        { name: { en: "Counseling", km: "ការប្រឹក្សា" }, level: 4 },
        { name: { en: "Empathy", km: "ការយល់ចិត្ត" }, level: 5 },
        { name: { en: "Case Management", km: "គ្រប់គ្រងករណី" }, level: 4 },
        { name: { en: "Community Outreach", km: "ការផ្សព្វផ្សាយសហគមន៍" }, level: 3 },
      ],
      incomeIntlMin: 1500, incomeIntlMax: 4000,
      educationPathEn: "Bachelor's in Social Work, Psychology, or related field required.",
      educationPathKm: "បរិញ្ញាបត្រសង្គមកិច្ច ចិត្តវិទ្យា ឬវិស័យពាក់ព័ន្ធតម្រូវ។",
      selfTaughtPossible: false,
      cambodiaDetailEn: "Strong demand from NGOs and government social services across all provinces.",
      cambodiaDetailKm: "តម្រូវការខ្ពស់ពី NGO និងសេវាសង្គមរដ្ឋាភិបាលទូទាំងគ្រប់ខេត្ត។",
      internationalDetailEn: "Limited without international qualifications.",
      internationalDetailKm: "មានកម្រិត បើគ្មានគុណវុឌ្ឍិអន្តរជាតិ។",
      remotePossible: false,
      growthExplanationEn: "Cambodia's social protection system is expanding. Government and NGOs investing in community-based services.",
      growthExplanationKm: "ប្រព័ន្ធការពារសង្គមកម្ពុជាកំពុងពង្រីក។ រដ្ឋាភិបាល និង NGO វិនិយោគក្នុងសេវាមូលដ្ឋានសហគមន៍។",
      careerPath: [
        { titleEn: "Social Work Assistant", titleKm: "ជំនួយការសង្គមកិច្ច", yearsEn: "0-2 yrs", yearsKm: "០-២ ឆ្នាំ", salaryEn: "$200-400", salaryKm: "$200-400" },
        { titleEn: "Social Worker", titleKm: "បុគ្គលិកសង្គមកិច្ច", yearsEn: "2-5 yrs", yearsKm: "២-៥ ឆ្នាំ", salaryEn: "$400-700", salaryKm: "$400-700" },
        { titleEn: "Senior / Program Lead", titleKm: "ជាន់ខ្ពស់ / អ្នកដឹកនាំកម្មវិធី", yearsEn: "5+ yrs", yearsKm: "៥+ ឆ្នាំ", salaryEn: "$700-1200", salaryKm: "$700-1200" },
      ],
      relatedPrograms: ["Social Science", "Education / Teaching"],
      relatedFields: ["Social Science"],
    },
  },
  {
    id: "environmental-specialist",
    nameEn: "Environmental Specialist",
    nameKm: "អ្នកជំនាញបរិស្ថាន",
    descriptionEn: "Protect natural resources and lead sustainability projects.",
    descriptionKm: "ការពារធនធានធម្មជាតិ និងដឹកនាំគម្រោងនិរន្តរភាព។",
    image: "/images/careers/environment.jpg",
    category: "social-impact",
    skills: [
      { en: "Research", km: "ស្រាវជ្រាវ" },
      { en: "Data Analysis", km: "វិភាគទិន្នន័យ" },
      { en: "Fieldwork", km: "ការងារវាល" },
    ],
    incomeMin: 400,
    incomeMax: 1200,
    educationLevel: "bachelor",
    cambodiaAvailable: true,
    internationalAvailable: true,
    growthScore: 5,
    filters: ["growthIndustry", "universityRequired"],
    interestTypes: ["social", "technology"],
    englishRequired: "intermediate",
    skillDifficulty: 4,
    detail: {
      taglineEn: "Save the planet, starting from Cambodia",
      taglineKm: "រក្សាភពផែនដី ចាប់ផ្តើមពីកម្ពុជា",
      jobDescriptionEn: "Conduct environmental assessments, monitor natural resources, lead conservation projects, and advise on sustainable development practices.",
      jobDescriptionKm: "ធ្វើការវាយតម្លៃបរិស្ថាន តាមដានធនធានធម្មជាតិ ដឹកនាំគម្រោងអភិរក្ស និងផ្តល់ដំបូន្មានលើអភិវឌ្ឍន៍និរន្តរភាព។",
      dailyTasksEn: ["Conduct field surveys", "Analyze environmental data", "Write impact assessment reports", "Coordinate with government agencies"],
      dailyTasksKm: ["ធ្វើការស្ទង់មតិវាល", "វិភាគទិន្នន័យបរិស្ថាន", "សរសេររបាយការណ៍វាយតម្លៃផលប៉ះពាល់", "សម្របសម្រួលជាមួយទីភ្នាក់ងាររដ្ឋាភិបាល"],
      detailedSkills: [
        { name: { en: "Environmental Science", km: "វិទ្យាសាស្ត្របរិស្ថាន" }, level: 4 },
        { name: { en: "Data Analysis / GIS", km: "វិភាគទិន្នន័យ / GIS" }, level: 4 },
        { name: { en: "Report Writing", km: "សរសេររបាយការណ៍" }, level: 4 },
        { name: { en: "Fieldwork", km: "ការងារវាល" }, level: 3 },
      ],
      incomeIntlMin: 2500, incomeIntlMax: 7000,
      educationPathEn: "Bachelor's in Environmental Science, Biology, or Geography required. Master's preferred for senior roles.",
      educationPathKm: "បរិញ្ញាបត្រវិទ្យាសាស្ត្របរិស្ថាន ជីវវិទ្យា ឬភូមិសាស្ត្រតម្រូវ។ អនុបណ្ឌិតត្រូវបានគេពេញចិត្តសម្រាប់មុខតំណែងជាន់ខ្ពស់។",
      selfTaughtPossible: false,
      cambodiaDetailEn: "Growing need for environmental protection as Cambodia develops. Tonle Sap, Cardamom Mountains, and coastal areas need specialists.",
      cambodiaDetailKm: "តម្រូវការកើនឡើងសម្រាប់ការការពារបរិស្ថានដោយសារកម្ពុជាកំពុងអភិវឌ្ឍ។",
      internationalDetailEn: "International NGOs, UN agencies, and consultancies hire environmental specialists globally.",
      internationalDetailKm: "NGO អន្តរជាតិ ទីភ្នាក់ងារ UN និងក្រុមហ៊ុនប្រឹក្សាជ្រើសរើសអ្នកជំនាញបរិស្ថានជាសកល។",
      remotePossible: false,
      growthExplanationEn: "Climate change is the defining challenge. Green jobs are the fastest-growing sector globally. Cambodia needs 10x more specialists.",
      growthExplanationKm: "ការប្រែប្រួលអាកាសធាតុជាបញ្ហាប្រឈមកំណត់។ ការងារបៃតងជាវិស័យរីកចម្រើនលឿនបំផុតជាសកល។",
      careerPath: [
        { titleEn: "Research Assistant", titleKm: "ជំនួយការស្រាវជ្រាវ", yearsEn: "0-2 yrs", yearsKm: "០-២ ឆ្នាំ", salaryEn: "$350-600", salaryKm: "$350-600" },
        { titleEn: "Environmental Officer", titleKm: "មន្រ្តីបរិស្ថាន", yearsEn: "2-5 yrs", yearsKm: "២-៥ ឆ្នាំ", salaryEn: "$600-1000", salaryKm: "$600-1000" },
        { titleEn: "Senior Specialist", titleKm: "អ្នកជំនាញជាន់ខ្ពស់", yearsEn: "5+ yrs", yearsKm: "៥+ ឆ្នាំ", salaryEn: "$1000-2000+", salaryKm: "$1000-2000+" },
      ],
      relatedPrograms: ["Agriculture", "Engineering"],
      relatedFields: ["Agriculture"],
    },
  },
];

export const MAX_INCOME = 2500;
